#!/usr/bin/env python3
"""Universal Chat Wrapper & Smart Router

Supports:
  - NVIDIA NIM models (glm-5.1, deepseek-v4-flash, nemotron, etc.)
  - OpenAI models
  - OpenRouter / local 9Router models (free/paid)
  - Smart Routing: Auto-selects the best NVIDIA free model based on task.
  - Dual-Tier Context: Instant context sniffing or deep codebase summarization.

Usage:
  ask "your prompt"          # Auto-routes with instant context
  ask --deep "your prompt"   # Scans and summarizes the codebase before routing
  chat gpt-4o                # Start interactive REPL with a specific model
"""
import os
import sys
import socket
import re
import json
import subprocess
import shutil
from openai import OpenAI
from dotenv import load_dotenv

# Load the env file to ensure all keys are accessible
load_dotenv(os.path.expanduser("~/Projects/investogram/.env"))
load_dotenv(os.path.expanduser("~/global.env"))

TEMP_MEM_FILE = ".rm_session.tmp"
SESSION_DIR = os.path.expanduser("~/Projects/RoutingMagic/sessions")

# Mapping of NVIDIA NIM models to their specific API keys
NVIDIA_API_MAP = {
    "nvidia/nemotron-3-ultra-550b-a55b": "NVAPI_KEY_NEMOTRON_ULTRA_550B",
    "deepseek-ai/deepseek-v4-flash": "NVAPI_KEY_DEEPSEEK_V4_FLASH",
    "moonshotai/kimi-k2.6": "NVAPI_KEY_KIMI_K2_6",
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": "NVAPI_KEY_NEMOTRON_OMNI_30B",
    "nvidia/nemotron-3.5-content-safety": "NVAPI_KEY_NEMOTRON_SAFETY",
    "mistralai/mistral-medium-3.5-128b": "NVAPI_KEY_MISTRAL_MEDIUM",
    "stepfun-ai/step-3.7-flash": "NVAPI_KEY_STEP_FLASH",
    "google/gemma-4-31b-it": "NVAPI_KEY_GEMMA_31B",
    "minimaxai/minimax-m2.7": "NVAPI_KEY_MINIMAX",
    "nvidia/cosmos3-nano-reasoner": "NVAPI_KEY_COSMOS",
    "nvidia/z-ai/glm-5.1": "NVAPI_KEY"
}

def get_instant_context():
    """Builds a ~150 token context string in milliseconds without calling any APIs."""
    cwd = os.getcwd()
    project_name = os.path.basename(cwd)
    tech_stack = []
    
    if os.path.exists("package.json"):
        try:
            with open("package.json", "r") as f:
                data = json.load(f)
                deps = list(data.get("dependencies", {}).keys()) + list(data.get("devDependencies", {}).keys())
                tech_stack.extend(deps[:15])
        except Exception:
            pass
    if os.path.exists("requirements.txt"):
        tech_stack.append("Python dependencies present")
        
    readme_snippet = ""
    if os.path.exists("README.md"):
        try:
            with open("README.md", "r") as f:
                lines = f.readlines()
                readme_snippet = "".join(lines[:5]).strip()
        except Exception:
            pass
            
    try:
        dirs = [d for d in os.listdir(".") if os.path.isdir(d) and not d.startswith(".")]
    except Exception:
        dirs = []
        
    context = f"Project Context:\n- Directory: {cwd} (Name: {project_name})\n"
    if tech_stack:
        context += f"- Tech Stack/Dependencies: {', '.join(tech_stack)}\n"
    if dirs:
        context += f"- Root Folders: {', '.join(dirs[:10])}\n"
    if readme_snippet:
        context += f"- README excerpt: {readme_snippet}\n"
        
    return context

def get_deep_context():
    """Builds a comprehensive codebase payload and uses a fast model to summarize it."""
    cwd = os.getcwd()
    project_name = os.path.basename(cwd)
    
    # 1. First priority: Check for documentation/history files generated by Claude Code
    history_files = ["memory.md", "progress.md", "scratchpad.md", "lessons.md"]
    found_docs = {}
    for f in history_files:
        if os.path.exists(f):
            try:
                with open(f, "r") as fd:
                    content_snippet = fd.read().strip()
                    if content_snippet:
                        found_docs[f] = content_snippet
            except Exception:
                pass
                
    if found_docs:
        print("\033[92m[Smart Router] Found project history files. Using them for deep context directly.\033[0m")
        combined_context = f"Project Deep Context (extracted from history files in {project_name}):\n\n"
        for name, data in found_docs.items():
            combined_context += f"=== {name} ===\n{data}\n\n"
        return combined_context

    # 2. Fallback: Standard scan & summarization
    content = f"Repository Context for {project_name}:\n\n"
    
    try:
        # Get tree of max 2 levels to avoid huge output
        tree_output = subprocess.check_output(["ls", "-R"], stderr=subprocess.DEVNULL, text=True)
        content += "Directory Tree:\n" + tree_output[:2000] + "\n\n"
    except Exception:
        pass
        
    files_to_read = ["README.md", "package.json", "schema.sql", "schema_v2.sql", "requirements.txt", "pyproject.toml"]
    for f in files_to_read:
        if os.path.exists(f):
            try:
                with open(f, "r") as fd:
                    content += f"--- {f} ---\n{fd.read()[:5000]}\n\n"
            except Exception:
                pass
                
    summarizer_models = ["deepseek-ai/deepseek-v4-flash", "google/gemma-4-31b-it", "mistralai/mistral-medium-3.5-128b"]
    prompt = f"Summarize the architecture, tech stack, and purpose of this codebase based on the following context. Be concise and focus on structural elements useful for a developer.\n\n{content}"
    
    print("\033[93m[Smart Router] Scanning codebase for deep context...\033[0m")
    
    for model in summarizer_models:
        try:
            client, target = get_client_and_model(model, is_summarizer=True)
            kwargs = {
                "model": target,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.3
            }
            if "deepseek-v4-flash" in target:
                kwargs["extra_body"] = {"chat_template_kwargs":{"thinking":True,"reasoning_effort":"low"}}
                
            resp = client.chat.completions.create(**kwargs)
            summary = resp.choices[0].message.content
            print(f"\033[92m[Smart Router] Codebase summarized via {model}.\033[0m")
            return f"Project Deep Context:\n{summary}"
        except Exception as e:
            print(f"\033[91m[Smart Router] Summarizer {model} failed. Trying next...\033[0m")
            
    print("\033[91m[Smart Router] All summarizer models failed. Falling back to instant context.\033[0m")
    return get_instant_context()

def is_port_open(ip, port):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(0.2)
    try:
        s.connect((ip, int(port)))
        s.close()
        return True
    except:
        return False

def smart_route(prompt):
    """Intelligently routes the prompt to the best available free model."""
    prompt_lower = prompt.lower()
    
    # Task 1: Deep Reasoning & Planning
    if re.search(r'\b(reason deeply|architecture|strategy|plan|tradeoffs|complex analysis|tool orchestration)\b', prompt_lower):
        return "nvidia/nemotron-3-ultra-550b-a55b", "deep_reasoning_planning"
        
    # Task 2: Fast Coding & Debugging
    if re.search(r'\b(code|fix bug|refactor|write function|regex|sql|snippet|debug|react|css|html)\b', prompt_lower):
        return "deepseek-ai/deepseek-v4-flash", "fast_coding"
        
    # Task 3: Long Horizon Agentic Coding
    if re.search(r'\b(large repo|multi-step coding|agent loop|tool use|long workflow|codebase reasoning)\b', prompt_lower):
        return "moonshotai/kimi-k2.6", "long_horizon_agentic_coding"
        
    # Task 4: Multimodal Reasoning (Fallback if triggered by text, though intended for images)
    if re.search(r'\b(image and text|video and text|multimodal reasoning)\b', prompt_lower):
        return "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning", "multimodal_reasoning"
        
    # Task 5: Safety Moderation
    if re.search(r'\b(moderation|toxicity|unsafe content|policy check|compliance screening)\b', prompt_lower):
        return "nvidia/nemotron-3.5-content-safety", "safety_moderation"
        
    # Task 6: Office Productivity
    if re.search(r'\b(office tasks|rewrite email|business drafting|document help)\b', prompt_lower):
        return "minimaxai/minimax-m2.7", "office_productivity"
        
    # Task 7: Budget Dense Reasoning
    if re.search(r'\b(small dense model|light reasoning|budget coding)\b', prompt_lower):
        return "google/gemma-4-31b-it", "budget_dense_reasoning"
        
    # Default: General Chat
    return "nvidia/z-ai/glm-5.1", "default_general"

def get_client_and_model(model_name, is_summarizer=False):
    clean_model = model_name
    
    # Use shorter timeout for summarizers to fail fast, longer for main response
    req_timeout = 10 if is_summarizer else 45
    
    # 1. NVIDIA NIM Models
    if model_name in NVIDIA_API_MAP or "nvidia" in model_name or "glm" in model_name or "deepseek" in model_name or "kimi" in model_name or "mistral" in model_name or "minimax" in model_name or "gemma" in model_name:
        if model_name.startswith("nvidia/"):
            clean_model = model_name.replace("nvidia/", "")
        else:
            clean_model = model_name
            
        key_env_var = NVIDIA_API_MAP.get(model_name, "NVAPI_KEY")
        api_key = os.getenv(key_env_var) or os.getenv("NVAPI_KEY") or os.getenv("NVIDIA_API_KEY")
        base_url = "https://integrate.api.nvidia.com/v1"
        return OpenAI(api_key=api_key, base_url=base_url, timeout=req_timeout), clean_model
        
    # 2. OpenAI
    if model_name.startswith("openai/") or model_name.startswith("gpt-") or model_name.startswith("o1-") or model_name.startswith("o3-"):
        if model_name.startswith("openai/"):
            clean_model = model_name.replace("openai/", "")
        api_key = os.getenv("OPENAI_API_KEY")
        return OpenAI(api_key=api_key, timeout=req_timeout), clean_model

    # 3. Fallback to OpenRouter / 9Router
    if is_port_open("127.0.0.1", 20128):
        base_url = "http://127.0.0.1:20128/v1"
        api_key = "9router-local"
    else:
        base_url = "https://openrouter.ai/api/v1"
        api_key = os.getenv("OPENROUTER_API_KEY") or os.getenv("9ROUTER_API_KEY")
        
    return OpenAI(api_key=api_key, base_url=base_url, timeout=req_timeout), model_name

def save_temp_memory(messages):
    try:
        with open(TEMP_MEM_FILE, "w") as f:
            json.dump(messages, f)
    except Exception:
        pass

def load_temp_memory():
    if os.path.exists(TEMP_MEM_FILE):
        try:
            with open(TEMP_MEM_FILE, "r") as f:
                return json.load(f)
        except Exception:
            pass
    return None

def generate_folder_name(messages):
    client, target = get_client_and_model("nvidia/z-ai/glm-5.1", is_summarizer=True)
    hist = json.dumps(messages[-6:])
    prompt = f"Based on this chat history, generate a short 2-4 word hyphenated folder name (like 'mutual-funds-refactor' or 'supabase-auth-fix'). Only output the folder name, nothing else.\n\n{hist}"
    try:
        resp = client.chat.completions.create(
            model=target,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2
        )
        name = resp.choices[0].message.content.strip()
        name = re.sub(r'[^a-zA-Z0-9\-]', '', name.replace(' ', '-').lower())
        return name if name else "saved-session"
    except:
        return "saved-session"

def compress_context(messages):
    if len(messages) <= 6:
        return messages
    
    # Keep system prompt
    sys_msg = messages[0]
    # Keep last 3 messages
    recent_msgs = messages[-3:]
    
    # Summarize the middle
    middle_msgs = messages[1:-3]
    hist = json.dumps(middle_msgs)
    
    client, target = get_client_and_model("nvidia/z-ai/glm-5.1", is_summarizer=True)
    prompt = f"Summarize the key technical decisions, bugs fixed, and current goal of this chat history. Be concise.\n\n{hist}"
    
    try:
        print("\n\033[93m[Smart Router] Compressing chat history to save tokens...\033[0m")
        resp = client.chat.completions.create(
            model=target,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3
        )
        summary = resp.choices[0].message.content.strip()
        print("\033[92m[Smart Router] Context compressed.\033[0m")
        
        return [
            sys_msg,
            {"role": "assistant", "content": f"[SYSTEM: Previous context summary]\n{summary}"}
        ] + recent_msgs
    except:
        return messages

def chat_oneshot(model, prompt, use_deep_context=False):
    if model == "smart":
        target_model, task_type = smart_route(prompt)
        print(f"\033[94m[Smart Router] Selected '{target_model}' for task type: {task_type}\033[0m")
    else:
        target_model = model

    # Determine Context
    if use_deep_context:
        context_str = get_deep_context()
    else:
        context_str = get_instant_context()

    system_message = {"role": "system", "content": f"You are a highly capable AI assistant helping a developer. Always incorporate the following project context into your answers to be as specific and useful as possible.\n\n{context_str}"}

    client, final_model_id = get_client_and_model(target_model)
    
    # Some models need specific parameters
    extra_body = {}
    if "nemotron-3-ultra" in final_model_id:
        extra_body = {"chat_template_kwargs":{"enable_thinking":True},"reasoning_budget":4096}
    elif "deepseek-v4-flash" in final_model_id:
        extra_body = {"chat_template_kwargs":{"thinking":True,"reasoning_effort":"high"}}
    
    kwargs = {
        "model": final_model_id,
        "messages": [system_message, {"role": "user", "content": prompt}],
        "temperature": 0.7,
        "stream": True
    }
    
    if extra_body:
        kwargs["extra_body"] = extra_body

    try:
        resp = client.chat.completions.create(**kwargs)
        for chunk in resp:
            if not getattr(chunk, "choices", None) or len(chunk.choices) == 0:
                continue
                
            delta = chunk.choices[0].delta
            
            # Print reasoning if available (DeepSeek/Nemotron)
            reasoning = getattr(delta, "reasoning_content", None)
            if reasoning:
                print(f"\033[90m{reasoning}\033[0m", end="", flush=True)
                
            if getattr(delta, "content", None):
                print(delta.content, end="", flush=True)
        print()
    except Exception as e:
        sys.stderr.write(f"\nRequest failed: {e}\n")
        
        # Fallback handling
        if model == "smart":
            print(f"\033[91m[Smart Router] Primary request failed. Falling back to glm-5.1 with INSTANT context to prevent loops...\033[0m")
            # CRITICAL FIX: Pass use_deep_context=False so we NEVER repeat the deep summarizer scan during a fallback
            chat_oneshot("nvidia/z-ai/glm-5.1", prompt, use_deep_context=False)
        else:
            sys.exit(1)

def handle_exit(messages):
    print("\nExiting.")
    ans = input("Session ended. Do you want to keep the memory file for next time? (y/N): ")
    if ans.lower() == 'y':
        folder_name = generate_folder_name(messages)
        os.makedirs(os.path.join(SESSION_DIR, folder_name), exist_ok=True)
        dest_path = os.path.join(SESSION_DIR, folder_name, "memory.md")
        if os.path.exists(TEMP_MEM_FILE):
            shutil.move(TEMP_MEM_FILE, dest_path)
        print(f"\033[92mSession saved to {dest_path}\033[0m")
    else:
        if os.path.exists(TEMP_MEM_FILE):
            os.remove(TEMP_MEM_FILE)
        print("Temporary session discarded.")

def repl(model, use_deep_context=False):
    if model != "smart":
        client, target_model = get_client_and_model(model)
        print(f"🦾 Universal Chat REPL — model: {model} (Target: {target_model})")
    else:
        client, target_model = None, None
        print(f"🧠 Smart Router REPL")
        
    print("Type your message. Exit with Ctrl-D or empty line.\n")
    
    messages = load_temp_memory()
    if messages:
        ans = input("Found an interrupted session memory. Do you want to resume from it? [Y/n]: ")
        if ans.lower() != 'n':
            print("Resumed session.")
            if model == "smart":
                target_model, task_type = smart_route(messages[-1]["content"] if len(messages)>1 else "resume")
                client, target_model = get_client_and_model(target_model)
        else:
            messages = None
            
    if not messages:
        if use_deep_context:
            context_str = get_deep_context()
        else:
            context_str = get_instant_context()
        messages = [{"role": "system", "content": f"You are a helpful assistant. Context:\n{context_str}"}]
        
    while True:
        try:
            line = input(">>> ")
        except (EOFError, KeyboardInterrupt):
            handle_exit(messages)
            break
            
        if not line.strip():
            continue
            
        if line.strip().lower() in ["exit", "quit", "/exit", "/quit"]:
            handle_exit(messages)
            break
            
        if model == "smart" and client is None:
            target_model, task_type = smart_route(line)
            print(f"\033[94m[Smart Router] Selected '{target_model}' for task type: {task_type}\033[0m")
            client, target_model = get_client_and_model(target_model)
            
        messages.append({"role": "user", "content": line})
        
        try:
            extra_body = {}
            if "nemotron-3-ultra" in target_model:
                extra_body = {"chat_template_kwargs": {"enable_thinking": True}, "reasoning_budget": 4096}
            elif "deepseek-v4-flash" in target_model:
                extra_body = {"chat_template_kwargs": {"thinking": True, "reasoning_effort": "high"}}

            # Print assistant prefix instantly so user knows a response is loading
            print("assistant: ", end="", flush=True)

            kwargs = {
                "model": target_model,
                "messages": messages,
                "temperature": 0.7,
                "stream": True
            }
            if extra_body:
                kwargs["extra_body"] = extra_body

            resp = client.chat.completions.create(**kwargs)
            
            assistant_reply = ""
            for chunk in resp:
                if not getattr(chunk, "choices", None) or len(chunk.choices) == 0:
                    continue
                delta = chunk.choices[0].delta
                
                # Stream reasoning / thinking content in gray if available
                reasoning = getattr(delta, "reasoning_content", None)
                if reasoning:
                    print(f"\033[90m{reasoning}\033[0m", end="", flush=True)
                    
                if getattr(delta, "content", None):
                    print(delta.content, end="", flush=True)
                    assistant_reply += delta.content
            print()
            
            messages.append({"role": "assistant", "content": assistant_reply})
            save_temp_memory(messages)
            
            if len(messages) > 8:
                messages = compress_context(messages)
                save_temp_memory(messages)
                
        except Exception as e:
            sys.stderr.write(f"\nRequest failed: {e}\n")
            messages.pop()

def main():
    if len(sys.argv) < 2:
        sys.stderr.write("Usage: openai_wrapper.py <model_id|smart> [--deep] [prompt...]\n")
        sys.exit(1)
        
    model_id = sys.argv[1]
    args = sys.argv[2:]
    
    use_deep = False
    if "--deep" in args:
        use_deep = True
        args.remove("--deep")
        
    if "--resume" in args:
        if not os.path.exists(SESSION_DIR):
            print("No saved sessions found.")
            sys.exit(0)
        sessions = [d for d in os.listdir(SESSION_DIR) if os.path.isdir(os.path.join(SESSION_DIR, d))]
        if not sessions:
            print("No saved sessions found.")
            sys.exit(0)
            
        print("Available Sessions:")
        for i, s in enumerate(sessions):
            print(f"[{i}] {s}")
        
        try:
            choice = int(input("Select session to resume: "))
            sel = sessions[choice]
            mem_path = os.path.join(SESSION_DIR, sel, "memory.md")
            shutil.copy(mem_path, TEMP_MEM_FILE)
            print(f"Loaded session {sel}.")
            repl(model_id, use_deep_context=use_deep)
        except Exception as e:
            print("Invalid selection.")
        sys.exit(0)
        
    if len(args) == 0:
        repl(model_id, use_deep_context=use_deep)
    else:
        prompt = " ".join(args)
        chat_oneshot(model_id, prompt, use_deep_context=use_deep)

if __name__ == "__main__":
    main()
