#!/usr/bin/env python3
"""Universal Chat Wrapper & Smart Router

Supports:
  - NVIDIA NIM models (glm-5.1, deepseek-v4-flash, nemotron, etc.)
  - OpenAI models
  - OpenRouter / local 9Router models (free/paid)
  - Smart Routing: Auto-selects the best NVIDIA free model based on task.
  - Dual-Tier Context: Instant context sniffing or deep codebase summarization.
  - Fallback loops, cost tracking, workspaces, failsafes, error interception.
"""
import os
import sys
import socket
import re
import json
import subprocess
import shutil
import time
import select
import shlex
import atexit
import tty
import termios
import concurrent.futures
import urllib.request
from pathlib import Path
from openai import OpenAI
from dotenv import load_dotenv

# --- Shell command security helpers ---
# Characters that enable subshell execution or command chaining.
# Deliberately narrow: blocks ; | & ` and $( ${ variable expansions and redirects < >
# Does NOT block bare $ (e.g. inside quoted strings like python3 -c "...$var...")
# because shell=False+shlex means the shell never interprets them.
_SHELL_DANGEROUS = re.compile(r'[;|&`<>]|\$[({]')

def _sanitize_cmd(cmd: str) -> tuple[bool, str]:
    """Return (is_safe, reason). Blocks shell metacharacters that enable injection.
    
    Allows: ls -la, npm start, python3 -c "...", VAR=x prog (shlex handles these safely)
    Blocks: rm -rf; echo, $(whoami), `id`, cat x | grep y, echo x > file
    """
    if _SHELL_DANGEROUS.search(cmd):
        return False, f"Blocked: command contains unsafe shell characters: {_SHELL_DANGEROUS.search(cmd).group()!r}"
    return True, ""

_SAFE_COMMIT_SHA: str | None = None

# Load the env file to ensure all keys are accessible
load_dotenv(os.path.expanduser("~/Projects/investogram/.env"))
load_dotenv(os.path.expanduser("~/global.env"))

WORKSPACE = "default"
TEMP_MEM_FILE = f".rm_session_{WORKSPACE}.json"
SESSION_DIR = os.path.expanduser("~/Projects/RoutingMagic/sessions")

SESSION_COST = 0.0
MAX_BUDGET = 5.0
PINNED_CONTEXT = []
request_timestamps = []
daily_requests = 0

# Mapping of NVIDIA NIM models to their specific API keys
NVIDIA_API_MAP = {
    "nvidia/nemotron-3-ultra-550b-a55b": "NVAPI_KEY_NEMOTRON_ULTRA_550B",
    "nvidia/llama-3.3-nemotron-super-49b-v1.5": "NVAPI_KEY_NEMOTRON_SUPER_49B",
    "nvidia/llama-3.1-nemotron-nano-vl-8b-v1": "NVAPI_KEY_NEMOTRON_VL_8B",
    "nvidia/nvidia-nemotron-nano-9b-v2": "NVAPI_KEY_NEMOTRON_NANO_9B",
    "nvidia/nemotron-ocr-v1": "NVAPI_KEY_NEMOTRON_OCR",
    "nvidia/nemotron-voicechat": "NVAPI_KEY_NEMOTRON_VOICECHAT",
    "nvidia/nv-embedqa-e5-v5": "NVAPI_KEY_NV_EMBEDQA",
    "deepseek-ai/deepseek-v4-flash": "NVAPI_KEY_DEEPSEEK_V4_FLASH",
    "moonshotai/kimi-k2.6": "NVAPI_KEY_KIMI_K2_6",
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": "NVAPI_KEY_NEMOTRON_OMNI_30B",
    "nvidia/nemotron-3.5-content-safety": "NVAPI_KEY_NEMOTRON_SAFETY",
    "mistralai/mistral-medium-3.5-128b": "NVAPI_KEY_MISTRAL_MEDIUM",
    "stepfun-ai/step-3.7-flash": "NVAPI_KEY_STEP_FLASH",
    "google/gemma-4-31b-it": "NVAPI_KEY_GEMMA_31B",
    "minimaxai/minimax-m2.7": "NVAPI_KEY_MINIMAX",
    "nvidia/cosmos3-nano-reasoner": "NVAPI_KEY_COSMOS",
    "nvidia/z-ai/glm-5.1": "NVAPI_KEY"
}

def get_instant_context():
    """Builds a ~150 token context string in milliseconds without calling any APIs."""
    cwd = os.getcwd()
    project_name = os.path.basename(cwd)
    tech_stack = []
    
    if os.path.exists("package.json"):
        try:
            with open("package.json", "r") as f:
                data = json.load(f)
                deps = list(data.get("dependencies", {}).keys()) + list(data.get("devDependencies", {}).keys())
                tech_stack.extend(deps[:15])
        except Exception:
            pass
    if os.path.exists("requirements.txt"):
        tech_stack.append("Python dependencies present")
        
    readme_snippet = ""
    if os.path.exists("README.md"):
        try:
            with open("README.md", "r") as f:
                lines = f.readlines()
                readme_snippet = "".join(lines[:5]).strip()
        except Exception:
            pass
            
    try:
        dirs = [d for d in os.listdir(".") if os.path.isdir(d) and not d.startswith(".")]
    except Exception:
        dirs = []
        
    context = f"Project Context:\n- Directory: {cwd} (Name: {project_name})\n"
    if tech_stack:
        context += f"- Tech Stack/Dependencies: {', '.join(tech_stack)}\n"
    if dirs:
        context += f"- Root Folders: {', '.join(dirs[:10])}\n"
    if readme_snippet:
        context += f"- README excerpt: {readme_snippet}\n"
        
    return context

def get_deep_context():
    """Builds a comprehensive codebase payload and uses a fast model to summarize it."""
    cwd = os.getcwd()
    project_name = os.path.basename(cwd)
    
    # 1. First priority: Check for documentation/history files generated by Claude Code
    history_files = ["memory.md", "progress.md", "scratchpad.md", "lessons.md"]
    found_docs = {}
    for f in history_files:
        if os.path.exists(f):
            try:
                with open(f, "r") as fd:
                    content_snippet = fd.read().strip()
                    if content_snippet:
                        found_docs[f] = content_snippet
            except Exception:
                pass
                
    if found_docs:
        print("\033[92m[Smart Router] Found project history files. Using them for deep context directly.\033[0m")
        combined_context = f"Project Deep Context (extracted from history files in {project_name}):\n\n"
        for name, data in found_docs.items():
            combined_context += f"=== {name} ===\n{data}\n\n"
        return combined_context

    # 2. Fallback: Standard scan & summarization
    content = f"Repository Context for {project_name}:\n\n"
    
    try:
        # Get tree of max 2 levels to avoid huge output
        tree_output = subprocess.check_output(["ls", "-R"], stderr=subprocess.DEVNULL, text=True)
        content += "Directory Tree:\n" + tree_output[:2000] + "\n\n"
    except Exception:
        pass
        
    files_to_read = ["README.md", "package.json", "schema.sql", "schema_v2.sql", "requirements.txt", "pyproject.toml"]
    for f in files_to_read:
        if os.path.exists(f):
            try:
                with open(f, "r") as fd:
                    content += f"--- {f} ---\n{fd.read()[:5000]}\n\n"
            except Exception:
                pass
                
    summarizer_models = ["deepseek-ai/deepseek-v4-flash", "google/gemma-4-31b-it", "mistralai/mistral-medium-3.5-128b"]
    prompt = f"Summarize the architecture, tech stack, and purpose of this codebase based on the following context. Be concise and focus on structural elements useful for a developer.\n\n{content}"
    
    print("\033[93m[Smart Router] Scanning codebase for deep context...\033[0m")
    
    for model in summarizer_models:
        try:
            client, target = get_client_and_model(model, is_summarizer=True)
            kwargs = {
                "model": target,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.3
            }
            if "deepseek-v4-flash" in target:
                kwargs["extra_body"] = {"chat_template_kwargs":{"thinking":True,"reasoning_effort":"low"}}
                
            resp = client.chat.completions.create(**kwargs)
            summary = resp.choices[0].message.content
            print(f"\033[92m[Smart Router] Codebase summarized via {model}.\033[0m")
            return f"Project Deep Context:\n{summary}"
        except Exception as e:
            print(f"\033[91m[Smart Router] Summarizer {model} failed. Trying next...\033[0m")
            
    print("\033[91m[Smart Router] All summarizer models failed. Falling back to instant context.\033[0m")
    return get_instant_context()

def is_port_open(ip, port):
    """Check if a TCP port is open. Uses context manager to ensure socket is always closed."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.2)
        try:
            s.connect((ip, int(port)))
            return True
        except Exception:
            return False

def check_clipboard_has_image():
    """Check if macOS clipboard contains an image format."""
    try:
        res = subprocess.run(["osascript", "-e", "clipboard info"], capture_output=True, text=True, timeout=6)
        if res.returncode != 0:
            print(f"\033[91m[Vision Debug] osascript failed with code {res.returncode}. Stderr: {res.stderr.strip()}\033[0m")
            return False
        info = res.stdout
        found = False
        for img_class in ["«class PNGf»", "PNGf", "JPEG picture", "GIF picture", "TIFF picture"]:
            if img_class in info:
                found = True
                break
        if not found:
            formats = info.replace("\n", " ").strip()
            print(f"\033[93m[Vision Debug] No image class found. Current clipboard contains: {formats}\033[0m")
        return found
    except Exception as e:
        print(f"\033[91m[Vision Debug] check_clipboard exception: {e}\033[0m")
    return False

def extract_clipboard_image(dest_path):
    """Write clipboard image data to dest_path using AppleScript.
    Returns the file extension (e.g. '.png') if successful, else None.
    """
    try:
        res = subprocess.run(["osascript", "-e", "clipboard info"], capture_output=True, text=True, timeout=6)
        if res.returncode != 0:
            print(f"\033[91m[Vision Debug] extract clipboard info failed with code {res.returncode}. Stderr: {res.stderr.strip()}\033[0m")
            return None
        info = res.stdout
        
        img_class = None
        ext = ".png"
        if "«class PNGf»" in info or "PNGf" in info:
            img_class = "«class PNGf»"
            ext = ".png"
        elif "JPEG picture" in info:
            img_class = "JPEG picture"
            ext = ".jpg"
        elif "TIFF picture" in info:
            img_class = "TIFF picture"
            ext = ".tiff"
        elif "GIF picture" in info:
            img_class = "GIF picture"
            ext = ".gif"
            
        if not img_class:
            print(f"\033[91m[Vision Debug] No compatible image class found for extraction. Clipboard info: {info.strip()}\033[0m")
            return None
            
        if os.path.exists(dest_path):
            try:
                os.remove(dest_path)
            except Exception:
                pass
                
        cmd = [
            "osascript",
            "-e", f'set f to open for access POSIX file "{dest_path}" with write permission',
            "-e", 'try',
            "-e", 'set eof f to 0',
            "-e", f'write (the clipboard as {img_class}) to f',
            "-e", 'close access f',
            "-e", 'on error e',
            "-e", 'try',
            "-e", 'close access f',
            "-e", 'end try',
            "-e", 'error e',
            "-e", 'end try'
        ]
        res2 = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        if res2.returncode == 0 and os.path.exists(dest_path) and os.path.getsize(dest_path) > 0:
            return ext
        else:
            print(f"\033[91m[Vision Debug] extract write command failed with code {res2.returncode}. Stderr: {res2.stderr.strip()}\033[0m")
    except Exception as e:
        print(f"\033[91m[Vision Debug] extract_clipboard exception: {e}\033[0m")
    return None

def run_vision_query(image_path, prompt, model_name=None):
    """Base64-encodes the image at image_path and queries a vision-capable model
    with a fallback chain.
    """
    import base64
    if not os.path.exists(image_path):
        print(f"\033[91mError: Image path {image_path} does not exist.\033[0m")
        return None
        
    try:
        with open(image_path, "rb") as f:
            base64_image = base64.b64encode(f.read()).decode("utf-8")
    except Exception as e:
        print(f"\033[91mError base64-encoding image: {e}\033[0m")
        return None
        
    ext = os.path.splitext(image_path)[1].lower()
    mime_type = "image/png"
    if ext in [".jpg", ".jpeg"]:
        mime_type = "image/jpeg"
    elif ext == ".gif":
        mime_type = "image/gif"
    elif ext == ".webp":
        mime_type = "image/webp"
        
    messages = [
        {
            "role": "user",
            "content": [
                {"type": "text", "text": prompt},
                {
                    "type": "image_url",
                    "image_url": {
                        "url": f"data:{mime_type};base64,{base64_image}"
                    }
                }
            ]
        }
    ]
    
    # Vision fallback chain
    vision_fallback = [
        "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
        "google/gemini-2.5-flash:free",
        "openai/gpt-4o-mini"
    ]
    if model_name:
        vision_fallback = [model_name] + [m for m in vision_fallback if m != model_name]
        
    resp = None
    selected_model = None
    for attempt in vision_fallback:
        try:
            client, selected_model = get_client_and_model(attempt)
            resp = client.chat.completions.create(
                model=selected_model,
                messages=messages,
                stream=True
            )
            break
        except Exception as e:
            continue
            
    if not resp:
        print("\033[91m[Vision] All vision models failed to start the request.\033[0m")
        return None
        
    print(f"\033[96m🤖 Vision ({selected_model}):\033[0m\n", end="", flush=True)
    assistant_reply = ""
    for chunk in resp:
        if not getattr(chunk, "choices", None) or len(chunk.choices) == 0:
            continue
        content = getattr(chunk.choices[0].delta, "content", None)
        if content:
            print(content, end="", flush=True)
            assistant_reply += content
    print()
    return assistant_reply

def smart_route(prompt):
    """Intelligently routes the prompt to the best available free model."""
    prompt_lower = prompt.lower()
    
    # 0. Council Deliberation -> Multi-agent council protocol
    if re.search(r'\b(council|deliberate|critically? audit|council-deliberation|llm-council|council deliberation)\b', prompt_lower):
        return "council", "llm_council_deliberation"
        
    # 1. Financial/Math Reasoning & Deep Logic -> DeepSeek R1 (free)
    if re.search(r'\b(math|financial analysis|deep reasoning|o1|complex logic|tradeoffs|step-by-step|chain of thought|deep analysis)\b', prompt_lower):
        return "nvidia/nemotron-3-super-120b-a12b:free", "financial_math_reasoning"
        
    # 2. Long Document RAG & Heavy Agentic Planning -> Nemotron 3 Super 120B
    if re.search(r'\b(large repo|long doc|architecture|strategy|plan|tool orchestration|codebase reasoning|massive context|rag|planning)\b', prompt_lower):
        return "nvidia/nemotron-3-super-120b-a12b:free", "long_context_agentic"
        
    # 3. Code Generation & Fixing -> Qwen3 Coder
    if re.search(r'\b(code|fix bug|refactor|write function|regex|sql|snippet|debug|react|css|html|typescript|python|script)\b', prompt_lower):
        return "qwen/qwen3-coder:free", "fast_coding"
        
    # 4. Agentic Workflows & Tool Use -> Llama 3.3 70B
    if re.search(r'\b(n8n|tool call|json extraction|workflow|extract data|structure this|json)\b', prompt_lower):
        return "meta-llama/llama-3.3-70b-instruct:free", "n8n_tool_calling"
        
    # 5. Vision / Chart Parsing -> Nemotron VL 8B
    if re.search(r'\b(image|chart|graph|vision|parse screenshot|look at this picture)\b', prompt_lower):
        return "nvidia/llama-3.1-nemotron-nano-vl-8b-v1", "stock_chart_vision"
        
    # 6. Financial Document OCR -> Nemotron OCR v1
    if re.search(r'\b(ocr|pdf|annual report|bse filing|table extraction|scan document)\b', prompt_lower):
        return "nvidia/nemotron-ocr-v1", "financial_doc_ocr"
        
    # 7. Voice / Audio -> Nemotron Voicechat
    if re.search(r'\b(voice|audio|speech|listen|transcribe)\b', prompt_lower):
        return "nvidia/nemotron-voicechat", "voice_trigger"

    # 8. Omni-modal fallback -> Nemotron Nano Omni 30B
    if re.search(r'\b(video|multimodal|omni)\b', prompt_lower):
        return "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning", "multimodal_omni"
        
    # Default General Tasks -> Gemma 4 31B (highest free quality score)
    return "google/gemma-4-31b-it:free", "default_general"

# Models that do NOT accept a temperature parameter
NO_TEMPERATURE_MODELS = {"o3-mini", "o1", "o1-mini", "o1-preview", "o3"}

def get_client_and_model(model_name, is_summarizer=False):
    clean_model = model_name
    # Ensure timeout is snappy so the user doesn't wait forever before failover
    req_timeout = 15 if is_summarizer else 25
    
    # NVIDIA NIM models — identified by presence in map, or by common vendor prefixes
    nvidia_vendors = ("nvidia/", "deepseek-ai/", "moonshotai/", "mistralai/", "google/gemma",
                      "minimaxai/", "stepfun-ai/", "glm")
    if (model_name in NVIDIA_API_MAP or any(model_name.startswith(v) for v in nvidia_vendors) or "glm" in model_name) and not model_name.endswith(":free"):
        # Strip the top-level "nvidia/" org prefix if present (e.g. nvidia/z-ai/glm-5.1 → z-ai/glm-5.1)
        if model_name.startswith("nvidia/") and model_name.count("/") >= 2:
            # e.g. "nvidia/z-ai/glm-5.1" → "z-ai/glm-5.1"
            clean_model = model_name[len("nvidia/"):]
        elif model_name.startswith("nvidia/") and model_name.count("/") == 1:
            # e.g. "nvidia/nemotron-..." — keep as is, NVIDIA API accepts the full ID
            clean_model = model_name
        else:
            clean_model = model_name
            
        key_env_var = NVIDIA_API_MAP.get(model_name, "NVAPI_KEY")
        api_key = os.getenv(key_env_var) or os.getenv("NVAPI_KEY") or os.getenv("NVIDIA_API_KEY")
        base_url = "https://integrate.api.nvidia.com/v1"
        return OpenAI(api_key=api_key, base_url=base_url, timeout=req_timeout), clean_model
    
    # OpenAI direct models (o3-mini, gpt-*, o1-*)
    if model_name.startswith("openai/") or model_name.startswith("gpt-") or model_name.startswith("o1") or model_name.startswith("o3"):
        if model_name.startswith("openai/"):
            clean_model = model_name[len("openai/"):]
        else:
            clean_model = model_name
        api_key = os.getenv("OPENAI_API_KEY")
        return OpenAI(api_key=api_key, timeout=req_timeout), clean_model

    # OpenRouter / 9router — model IDs must NOT have an 'openrouter/' prefix
    # Strip it if accidentally present (e.g. "openrouter/google/gemma..." → "google/gemma...")
    if model_name.startswith("openrouter/"):
        clean_model = model_name[len("openrouter/"):]
    else:
        clean_model = model_name

    if is_port_open("127.0.0.1", 20128):
        base_url = "http://127.0.0.1:20128/v1"
        api_key = "9router-local"
    else:
        base_url = "https://openrouter.ai/api/v1"
        api_key = os.getenv("OPENROUTER_API_KEY") or os.getenv("9ROUTER_API_KEY")
        
    return OpenAI(api_key=api_key, base_url=base_url, timeout=req_timeout), clean_model

def save_temp_memory(messages):
    try:
        with open(TEMP_MEM_FILE, "w") as f:
            json.dump(messages, f)
    except Exception:
        pass

def load_temp_memory():
    if os.path.exists(TEMP_MEM_FILE):
        try:
            with open(TEMP_MEM_FILE, "r") as f:
                return json.load(f)
        except Exception:
            pass
    return None



def compress_context(messages):
    if len(messages) <= 6:
        return messages
    
    sys_msg = messages[0]
    recent_msgs = messages[-3:]
    middle_msgs = messages[1:-3]
    hist = json.dumps(middle_msgs)
    
    prompt = f"Summarize the key technical decisions, bugs fixed, and current goal of this chat history. Be concise.\n\n{hist}"
    
    fallback_chain = ["google/gemma-4-31b-it:free", "nvidia/nemotron-3-super-120b-a12b:free", "qwen/qwen3-coder:free"]
    summary = None
    
    for target_model in fallback_chain:
        try:
            client, target = get_client_and_model(target_model, is_summarizer=True)
            resp = client.chat.completions.create(
                model=target,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3
            )
            summary = resp.choices[0].message.content.strip()
            print(f"\033[92m[Smart Router] Context compressed via {target_model}.\033[0m")
            break
        except Exception as e:
            continue
            
    if not summary:
        return messages
        
    return [
        sys_msg,
        {"role": "assistant", "content": f"[SYSTEM: Previous context summary]\n{summary}"}
    ] + recent_msgs

def chat_oneshot(model, prompt, use_deep_context=False):
    if model == "smart":
        target_model, task_type = smart_route(prompt)
        print(f"\033[94m[Smart Router] Selected '{target_model}' for task type: {task_type}\033[0m")
    else:
        target_model = model

    if use_deep_context:
        context_str = get_deep_context()
    else:
        context_str = get_instant_context()

    system_instruction = (
        "You are a rigorous analytical assistant trained on Charlie Munger's mental models. "
        "1. INVERSION: Identify failure paths and how to avoid them.\n"
        "2. FIRST PRINCIPLES: Strip away assumptions; answer from the irreducible truth.\n"
        "3. NO FLUFF: Avoid generic advice. Give clear, specific, actionable insights.\n"
        f"Context:\n{context_str}"
    )
    system_message = {"role": "system", "content": system_instruction}


    fallback_chain = [target_model, "google/gemma-4-31b-it:free", "nvidia/nemotron-3-super-120b-a12b:free", "openai/gpt-oss-120b:free", "qwen/qwen3-coder:free", "meta-llama/llama-3.3-70b-instruct:free", "gemini-2.5-pro"]
    seen = set()
    fallback_chain = [x for x in fallback_chain if not (x in seen or seen.add(x))]

    success = False
    for attempt_model in fallback_chain:
        if attempt_model == "council":
            try:
                run_council(prompt, use_deep_context=use_deep_context)
                success = True
                break
            except Exception as e:
                print(f"\n\033[91m[Error with council] {e}\033[0m")
                if attempt_model != fallback_chain[-1]:
                    print("\033[93mTrying fallback model...\033[0m")
                continue

        try:
            temp_client, final_model_id = get_client_and_model(attempt_model)
            
            extra_body = {}
            if "nemotron-3-ultra" in final_model_id:
                extra_body = {"chat_template_kwargs":{"enable_thinking":True},"reasoning_budget":4096}
            elif "deepseek-v4-flash" in final_model_id:
                extra_body = {"chat_template_kwargs":{"thinking":True,"reasoning_effort":"high"}}
            
            base_model_id = final_model_id.split("/")[-1].split(":")[0]
            supports_temperature = base_model_id not in NO_TEMPERATURE_MODELS
            
            kwargs = {
                "model": final_model_id,
                "messages": [system_message, {"role": "user", "content": prompt}],
                "stream": True
            }
            if supports_temperature:
                kwargs["temperature"] = 0.7
            if extra_body:
                kwargs["extra_body"] = extra_body

            print(f"\n\033[96m🤖 assistant ({final_model_id}):\033[0m\n", end="", flush=True)
            resp = temp_client.chat.completions.create(**kwargs)
            was_reasoning = False
            reasoning_start_time = None
            accumulated_reasoning = ""
            for chunk in resp:
                if not getattr(chunk, "choices", None) or len(chunk.choices) == 0:
                    continue
                    
                delta = chunk.choices[0].delta
                reasoning = getattr(delta, "reasoning_content", None)
                if reasoning:
                    if not was_reasoning:
                        was_reasoning = True
                        reasoning_start_time = time.time()
                        accumulated_reasoning = ""
                    accumulated_reasoning += reasoning
                    elapsed = time.time() - reasoning_start_time
                    snippet = accumulated_reasoning.replace("\n", " ").replace("\r", " ")
                    if len(snippet) > 60:
                        snippet = "..." + snippet[-57:]
                    sys.stdout.write(f"\r\033[K\033[90m[Thinking {elapsed:.1f}s] {snippet}\033[0m")
                    sys.stdout.flush()
                    
                content = getattr(delta, "content", None)
                if content:
                    if was_reasoning:
                        sys.stdout.write("\r\033[K")
                        sys.stdout.flush()
                        was_reasoning = False
                        
                    print(content, end="", flush=True)
            if was_reasoning:
                sys.stdout.write("\r\033[K")
                sys.stdout.flush()
            print()
            success = True
            break
        except Exception as e:
            print(f"\n\033[91m[Error with {attempt_model}] {e}\033[0m")
            if attempt_model != fallback_chain[-1]:
                print("\033[93mTrying fallback model...\033[0m")
            continue
            
    if not success:
        raise RuntimeError("All models in the fallback chain failed for chat_oneshot.")


def avg_price_per_m(model):
    """Calculate average price per million tokens."""
    p = model.get("pricing", {}) or {}
    try:
        prompt = float(p.get("prompt", 0) or 0)
        completion = float(p.get("completion", 0) or 0)
    except (TypeError, ValueError):
        return float("inf")
    if prompt < 0 or completion < 0:
        return float("inf")
    return (prompt + completion) / 2.0 * 1_000_000.0

def get_dynamic_model(models_list, free=True, price_ceiling=None, required_params=None, min_context=128000, fallback_default=None):
    """Dynamically selects the latest model passing the criteria from the registry."""
    if not models_list:
        return fallback_default

    passers = []
    for m in models_list:
        # Check pricing
        ap = avg_price_per_m(m)
        if free:
            if ap != 0.0:
                continue
        else:
            if ap == float("inf"):
                continue
            if price_ceiling is not None and ap > price_ceiling:
                continue
                
        # Check context length
        if (m.get("context_length") or 0) < min_context:
            continue
            
        # Check supported parameters
        sp = set(m.get("supported_parameters", []) or [])
        if required_params:
            if not set(required_params).issubset(sp):
                continue
                
        passers.append(m)

    if not passers:
        return fallback_default

    # Sort candidates DESC:
    # 1. Has structured outputs
    # 2. Created timestamp (latest first)
    # 3. Cheapest first (-avg_price)
    # 4. Context length (larger first)
    def sort_key(model):
        sp = set(model.get("supported_parameters", []) or [])
        has_struct = 1 if "structured_outputs" in sp else 0
        created = model.get("created") or 0
        neg_price = -avg_price_per_m(model)
        ctx = model.get("context_length") or 0
        return (has_struct, created, neg_price, ctx)

    passers.sort(key=sort_key, reverse=True)
    return passers[0]["id"]


def _query_model(model_name, messages, temperature=0.7):
    client, target_model = get_client_and_model(model_name)
    base_model_id = target_model.split("/")[-1].split(":")[0]
    supports_temperature = base_model_id not in NO_TEMPERATURE_MODELS
    
    kwargs = {
        "model": target_model,
        "messages": messages,
    }
    if supports_temperature:
        kwargs["temperature"] = temperature
        
    extra_body = {}
    if "nemotron-3-ultra" in target_model:
        extra_body = {"chat_template_kwargs": {"enable_thinking": True}, "reasoning_budget": 4096}
    elif "deepseek-v4-flash" in target_model:
        extra_body = {"chat_template_kwargs": {"thinking": True, "reasoning_effort": "high"}}
        
    if extra_body:
        kwargs["extra_body"] = extra_body
        
    resp = client.chat.completions.create(**kwargs)
    if resp is None:
        raise RuntimeError("OpenRouter returned None response.")
    choices = getattr(resp, "choices", None)
    if choices is None:
        raise RuntimeError("OpenRouter response choices field is None.")
    if len(choices) == 0:
        raise RuntimeError("OpenRouter response choices list is empty.")
    choice = choices[0]
    if choice is None:
        raise RuntimeError("OpenRouter response first choice is None.")
    message = getattr(choice, "message", None)
    if message is None:
        raise RuntimeError("OpenRouter response choice message is None.")
    content = getattr(message, "content", None)
    if content is None:
        raise RuntimeError("OpenRouter response choice message content is None.")
    return content

def _query_model_with_timing(model_name, messages, temperature=0.7):
    start_time = time.time()
    try:
        content = _query_model(model_name, messages, temperature)
        elapsed = time.time() - start_time
        return model_name, content, None, elapsed
    except Exception as e:
        elapsed = time.time() - start_time
        return model_name, None, str(e), elapsed

def _query_model_with_fallback_and_timing(model_name, messages, temperature=0.7, excluded_models=None):
    if excluded_models is None:
        excluded_models = set()
    start_time = time.time()
    
    # We will try the primary model first, and then fallback to other free models if it fails.
    attempts = [model_name]
    
    # Standard free backup pool
    fallbacks = [
        "google/gemma-4-31b-it:free",
        "qwen/qwen3-coder:free",
        "meta-llama/llama-3.3-70b-instruct:free",
        "nvidia/nemotron-3-super-120b-a12b:free",
        "google/gemma-2-9b-it:free",
        "qwen/qwen-2.5-coder-32b-instruct:free",
        "meta-llama/llama-3-8b-instruct:free",
        "microsoft/phi-3-medium-128k-instruct:free"
    ]
    
    for f in fallbacks:
        if f not in attempts and f not in excluded_models:
            attempts.append(f)
            
    last_err = None
    failed_attempts = []
    
    for attempt in attempts:
        try:
            content = _query_model(attempt, messages, temperature)
            elapsed = time.time() - start_time
            return attempt, content, None, elapsed, failed_attempts
        except Exception as e:
            failed_attempts.append((attempt, str(e)))
            last_err = e
            continue
            
    elapsed = time.time() - start_time
    return model_name, None, str(last_err), elapsed, failed_attempts

def run_council(prompt, use_deep_context=False):
    """Executes Karpathy-style LLM Council deliberation protocol:
    Stage 1: parallel opinions from 4 free models.
    Stage 2: parallel peer critique and scoring (1-10).
    Stage 3: synthesis by the Chairman model (dynamic latest reasoning model for heavy queries, otherwise latest free general model).
    """
    import concurrent.futures
    import urllib.request
    
    # Fetch live models from OpenRouter registry to prevent static model rot
    models_list = None
    try:
        url = "https://openrouter.ai/api/v1/models"
        req = urllib.request.Request(url, headers={"User-Agent": "RoutingMagic/1.0"})
        with urllib.request.urlopen(req, timeout=5) as resp:
            models_list = json.loads(resp.read())["data"]
            print("\033[92m[LLM Council] Successfully fetched live model registry from OpenRouter.\033[0m")
    except Exception as e:
        print(f"\033[93m[LLM Council] Warning: Live registry fetch failed ({e}). Using hardcoded model defaults.\033[0m")

    # Classify prompt for specialty prioritizing
    prompt_lower = prompt.lower()
    if re.search(r'\b(math|logic|proof|prove|algorithm|complex logic|equation|derivation|reason|step-by-step|step by step|chain of thought|deep reasoning|o1|critically audit|audit)\b', prompt_lower):
        category = "reasoning"
    elif re.search(r'\b(code|coding|frontend|backend|fastapi|react|tailwind|html|css|javascript|python|java|c\+\+|bug|exception|compile|syntax|refactor|endpoint|api|database|sql)\b', prompt_lower):
        category = "coding"
    elif re.search(r'\b(agent|mcp|tool|function|json|xml|yaml|parse|schema|structure|pipeline|webhook|automate|integration)\b', prompt_lower):
        category = "agentic"
    else:
        category = "general"

    def select_coder(models, excluded_set):
        for m in models:
            m_id = m.get("id", "").lower()
            if m_id in excluded_set:
                continue
            if "coder" in m_id or "code" in m_id:
                if avg_price_per_m(m) == 0.0:
                    return m["id"]
        filtered = [m for m in models if m.get("id") not in excluded_set]
        return get_dynamic_model(filtered, free=True, required_params=["structured_outputs"], fallback_default="qwen/qwen3-coder:free")

    def select_reasoning(models, excluded_set):
        for m in models:
            m_id = m.get("id", "").lower()
            if m_id in excluded_set:
                continue
            sp = set(m.get("supported_parameters", []) or [])
            if "reasoning" in sp:
                if avg_price_per_m(m) == 0.0:
                    return m["id"]
        filtered = [m for m in models if m.get("id") not in excluded_set]
        return get_dynamic_model(filtered, free=True, required_params=["reasoning"], fallback_default="nvidia/nemotron-3-super-120b-a12b:free")

    def select_agentic(models, excluded_set):
        for m in models:
            m_id = m.get("id", "").lower()
            if m_id in excluded_set:
                continue
            sp = set(m.get("supported_parameters", []) or [])
            if "structured_outputs" in sp or "tools" in sp:
                if avg_price_per_m(m) == 0.0:
                    return m["id"]
        filtered = [m for m in models if m.get("id") not in excluded_set]
        return get_dynamic_model(filtered, free=True, fallback_default="meta-llama/llama-3.3-70b-instruct:free")

    def select_general(models, excluded_set):
        for m in models:
            m_id = m.get("id", "").lower()
            if m_id in excluded_set:
                continue
            if "gemma" in m_id or "llama" in m_id:
                if avg_price_per_m(m) == 0.0:
                    return m["id"]
        filtered = [m for m in models if m.get("id") not in excluded_set]
        return get_dynamic_model(filtered, free=True, fallback_default="google/gemma-4-31b-it:free")

    # Dynamically select 3 distinct council models
    council_models = []
    excluded = set()
    if models_list:
        try:
            if category == "coding":
                m1 = select_coder(models_list, excluded)
                council_models.append(m1)
                excluded.add(m1)
                m2 = select_reasoning(models_list, excluded)
                council_models.append(m2)
                excluded.add(m2)
                m3 = select_general(models_list, excluded)
                council_models.append(m3)
                excluded.add(m3)
            elif category == "reasoning":
                m1 = select_reasoning(models_list, excluded)
                council_models.append(m1)
                excluded.add(m1)
                m2 = select_general(models_list, excluded)
                council_models.append(m2)
                excluded.add(m2)
                m3 = select_coder(models_list, excluded)
                council_models.append(m3)
                excluded.add(m3)
            elif category == "agentic":
                m1 = select_agentic(models_list, excluded)
                council_models.append(m1)
                excluded.add(m1)
                m2 = select_coder(models_list, excluded)
                council_models.append(m2)
                excluded.add(m2)
                m3 = select_reasoning(models_list, excluded)
                council_models.append(m3)
                excluded.add(m3)
            else:
                m1 = select_general(models_list, excluded)
                council_models.append(m1)
                excluded.add(m1)
                m2 = select_reasoning(models_list, excluded)
                council_models.append(m2)
                excluded.add(m2)
                m3 = select_coder(models_list, excluded)
                council_models.append(m3)
                excluded.add(m3)
                
            fallback_options = [
                "google/gemma-4-31b-it:free",
                "qwen/qwen3-coder:free",
                "nvidia/nemotron-3-super-120b-a12b:free",
                "meta-llama/llama-3.3-70b-instruct:free",
                "google/gemma-2-9b-it:free"
            ]
            for fb in fallback_options:
                if len(council_models) >= 3:
                    break
                if fb not in council_models:
                    council_models.append(fb)
        except Exception as e:
            print(f"\033[93m[LLM Council] Error selecting dynamic council models: {e}. Using defaults.\033[0m")
            council_models = [
                "google/gemma-4-31b-it:free",
                "qwen/qwen3-coder:free",
                "nvidia/nemotron-3-super-120b-a12b:free"
            ]
    else:
        council_models = [
            "google/gemma-4-31b-it:free",
            "qwen/qwen3-coder:free",
            "nvidia/nemotron-3-super-120b-a12b:free"
        ]

    context_str = get_deep_context() if use_deep_context else get_instant_context()
    system_instruction = (
        "You are a rigorous analytical assistant trained on Charlie Munger's mental models. "
        "1. INVERSION: Identify failure paths and how to avoid them.\n"
        "2. FIRST PRINCIPLES: Strip away assumptions; answer from the irreducible truth.\n"
        "3. NO FLUFF: Avoid generic advice. Give clear, specific, actionable insights.\n"
        f"Context:\n{context_str}"
    )
    
    # Select Chairman based on regex heuristics (supports trade-offs with hyphens)
    is_high_reasoning = bool(re.search(
        r'\b(math|financial analysis|deep reasoning|o1|complex logic|tradeoffs|trade-offs|step-by-step|chain of thought|deep analysis|critically audit|audit|algorithm|proof|prove|equation|derivation)\b',
        prompt.lower()
    ))
    
    if is_high_reasoning:
        # Dynamically choose the latest paid reasoning model under $3.00/M tokens ceiling
        chairman_model = get_dynamic_model(models_list, free=False, price_ceiling=3.0, required_params=["reasoning"],
                                           fallback_default="openai/o3-mini")
        reasoning_reason = f"high reasoning required (regex matched) -> selected latest {chairman_model}"
    else:
        # Dynamically choose the latest free flagship model
        chairman_model = get_dynamic_model(models_list, free=True, fallback_default="google/gemma-4-31b-it:free")
        reasoning_reason = f"general query -> selected latest {chairman_model}"
        
    print("\n\033[95m[LLM Council] Starting deliberation...\033[0m")
    print(f"\033[94m[Stage 1] Querying 4 council members {council_models} for opinions in parallel...\033[0m")
    
    stage1_start = time.time()
    opinions = {}
    stage1_messages = [
        {"role": "system", "content": system_instruction},
        {"role": "user", "content": prompt}
    ]
    
    with concurrent.futures.ThreadPoolExecutor(max_workers=len(council_models)) as executor:
        futures = {executor.submit(_query_model_with_fallback_and_timing, m, stage1_messages, 0.7, set(council_models)): m for m in council_models}
        for future in concurrent.futures.as_completed(futures):
            orig_model = futures[future]
            succeeded_model, content, err, elapsed, failed_attempts = future.result()
            
            # Print failures for this slot
            for failed_m, failed_e in failed_attempts:
                print(f"  \033[91m✗ {failed_m} failed to reply: {failed_e}\033[0m")
                
            if err:
                print(f"  \033[91m✗ All fallbacks failed for slot {orig_model} [{elapsed:.2f}s]\033[0m")
            else:
                if succeeded_model != orig_model:
                    print(f"  \033[92m✓ {orig_model} failed, successfully fell back to {succeeded_model} [{elapsed:.2f}s]\033[0m")
                else:
                    print(f"  \033[92m✓ {succeeded_model} completed [{elapsed:.2f}s]\033[0m")
                opinions[succeeded_model] = content
                
    stage1_duration = time.time() - stage1_start
    print(f"\033[94m[Stage 1] Completed in {stage1_duration:.2f}s\033[0m\n")
    
    if not opinions:
        print("\033[91m[LLM Council] Warning: All council models failed in Stage 1. Falling back to direct Chairman query.\033[0m")
        # Direct Chairman query fallback
        chairman_fallbacks = [
            chairman_model,
            "openai/o3-mini",
            "google/gemma-4-31b-it:free",
            "meta-llama/llama-3.3-70b-instruct:free",
            "nvidia/nemotron-3-super-120b-a12b:free"
        ]
        resp = None
        target_model = None
        for attempt in chairman_fallbacks:
            try:
                client, target_model = get_client_and_model(attempt)
                kwargs = {
                    "model": target_model,
                    "messages": [
                        {"role": "system", "content": system_instruction},
                        {"role": "user", "content": prompt}
                    ],
                    "stream": True
                }
                base_model_id = target_model.split("/")[-1].split(":")[0]
                if base_model_id not in NO_TEMPERATURE_MODELS:
                    kwargs["temperature"] = 0.7
                
                extra_body = {}
                if "nemotron-3-ultra" in target_model:
                    extra_body = {"chat_template_kwargs": {"enable_thinking": True}, "reasoning_budget": 4096}
                elif "deepseek-v4-flash" in target_model:
                    extra_body = {"chat_template_kwargs": {"thinking": True, "reasoning_effort": "high"}}
                if extra_body:
                    kwargs["extra_body"] = extra_body
                    
                resp = client.chat.completions.create(**kwargs)
                break
            except Exception as e:
                print(f"\033[91mChairman fallback attempt {attempt} failed to start: {e}. Trying fallback...\033[0m")
                continue
                
        if not resp:
            raise RuntimeError("All Chairman fallback attempts failed to start.")
            
        print(f"\033[96m🤖 Chairman ({target_model}):\033[0m\n", end="", flush=True)
        assistant_reply = ""
        was_reasoning = False
        reasoning_start_time = None
        accumulated_reasoning = ""
        for chunk in resp:
            if not getattr(chunk, "choices", None) or len(chunk.choices) == 0:
                continue
            delta = chunk.choices[0].delta
            
            reasoning = getattr(delta, "reasoning_content", None)
            if reasoning:
                if not was_reasoning:
                    was_reasoning = True
                    reasoning_start_time = time.time()
                    accumulated_reasoning = ""
                accumulated_reasoning += reasoning
                elapsed = time.time() - reasoning_start_time
                snippet = accumulated_reasoning.replace("\n", " ").replace("\r", " ")
                if len(snippet) > 60:
                    snippet = "..." + snippet[-57:]
                sys.stdout.write(f"\r\033[K\033[90m[Thinking {elapsed:.1f}s] {snippet}\033[0m")
                sys.stdout.flush()
                
            content = getattr(delta, "content", None)
            if content:
                if was_reasoning:
                    sys.stdout.write("\r\033[K")
                    sys.stdout.flush()
                    was_reasoning = False
                print(content, end="", flush=True)
                assistant_reply += content
                
        if was_reasoning:
            sys.stdout.write("\r\033[K")
            sys.stdout.flush()
        print()
        return assistant_reply

    # Stage 2: Peer Review
    print("\033[94m[Stage 2] Running anonymized peer reviews & scoring in parallel...\033[0m")
    stage2_start = time.time()
    
    anonymized_opinions = []
    response_to_model = {}
    for i, (model_name, content) in enumerate(opinions.items(), 1):
        label = f"Response {i}"
        anonymized_opinions.append((label, content))
        response_to_model[label] = model_name
        
    opinions_block = ""
    for label, content in anonymized_opinions:
        opinions_block += f"=== {label} ===\n{content}\n\n"
        
    peer_review_user_prompt = (
        f"You are part of an LLM Council deliberating on the user's prompt: \"{prompt}\".\n\n"
        "Here are the responses generated by other council members (anonymized):\n\n"
        f"{opinions_block}"
        "Please critically evaluate each response. For each response, do the following:\n"
        "1. Identify any errors, flawed assumptions, or missing details.\n"
        "2. Provide constructive suggestions for improvement.\n"
        "3. Assign a quantitative score from 1 to 10 based on accuracy, depth, and usefulness.\n\n"
        "Present your review clearly and objectively. Use the labels (Response 1, Response 2, etc.) to reference each response."
    )
    
    peer_review_messages = [
        {"role": "system", "content": system_instruction},
        {"role": "user", "content": peer_review_user_prompt}
    ]
    
    reviews = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=len(opinions)) as executor:
        futures = {executor.submit(_query_model_with_fallback_and_timing, m, peer_review_messages, 0.7, set(opinions.keys())): m for m in opinions.keys()}
        for future in concurrent.futures.as_completed(futures):
            orig_model = futures[future]
            succeeded_model, content, err, elapsed, failed_attempts = future.result()
            
            # Print failures for this review slot
            for failed_m, failed_e in failed_attempts:
                print(f"  \033[91m✗ {failed_m} review failed: {failed_e}\033[0m")
                
            if err:
                print(f"  \033[91m✗ All fallbacks failed for review by {orig_model} [{elapsed:.2f}s]\033[0m")
            else:
                if succeeded_model != orig_model:
                    print(f"  \033[92m✓ {orig_model} review failed, successfully fell back to {succeeded_model} [{elapsed:.2f}s]\033[0m")
                else:
                    print(f"  \033[92m✓ {succeeded_model} review completed [{elapsed:.2f}s]\033[0m")
                reviews[succeeded_model] = content
                
    stage2_duration = time.time() - stage2_start
    print(f"\033[94m[Stage 2] Completed in {stage2_duration:.2f}s\033[0m\n")
    
    # Stage 3: Synthesis by Chairman
    print(f"\033[94m[Stage 3] Synthesizing final response via Chairman: {chairman_model} ({reasoning_reason})...\033[0m\n")
    
    council_deliberation_content = ""
    for label, content in anonymized_opinions:
        model_name = response_to_model[label]
        review_text = reviews.get(model_name, "No review available.")
        council_deliberation_content += f"=== Council Member: {model_name} (Anonymized as {label}) ===\n"
        council_deliberation_content += f"Original Response:\n{content}\n\n"
        council_deliberation_content += f"Peer Critique provided by this member:\n{review_text}\n\n"
        council_deliberation_content += "=" * 40 + "\n\n"
        
    chairman_user_prompt = (
        f"You are the Chairman of the LLM Council. Your task is to synthesize the final response to the user's prompt based on the deliberation of the council members.\n\n"
        f"User Prompt: \"{prompt}\"\n\n"
        "Here are the responses and peer critiques from the council members:\n\n"
        f"{council_deliberation_content}"
        "Analyze the responses and peer critiques, identify the best points, correct any errors, and synthesize a single, unified, high-quality final response. Do not just summarize the opinions; produce the absolute best, most accurate, and most comprehensive answer to the user's prompt.\n\n"
        "Focus on inversion, first principles, and actionable, high-quality developer insights. Output the final synthesized response directly."
    )
    
    chairman_fallbacks = [
        chairman_model,
        "openai/o3-mini",
        "google/gemma-4-31b-it:free",
        "meta-llama/llama-3.3-70b-instruct:free",
        "nvidia/nemotron-3-super-120b-a12b:free"
    ]
    resp = None
    target_model = None
    for attempt in chairman_fallbacks:
        try:
            client, target_model = get_client_and_model(attempt)
            kwargs = {
                "model": target_model,
                "messages": [
                    {"role": "system", "content": system_instruction},
                    {"role": "user", "content": chairman_user_prompt}
                ],
                "stream": True
            }
            base_model_id = target_model.split("/")[-1].split(":")[0]
            supports_temperature = base_model_id not in NO_TEMPERATURE_MODELS
            if supports_temperature:
                kwargs["temperature"] = 0.7
                
            extra_body = {}
            if "nemotron-3-ultra" in target_model:
                extra_body = {"chat_template_kwargs": {"enable_thinking": True}, "reasoning_budget": 4096}
            elif "deepseek-v4-flash" in target_model:
                extra_body = {"chat_template_kwargs": {"thinking": True, "reasoning_effort": "high"}}
            if extra_body:
                kwargs["extra_body"] = extra_body
                
            resp = client.chat.completions.create(**kwargs)
            break
        except Exception as e:
            print(f"\033[91mChairman model attempt {attempt} failed to start: {e}. Trying fallback...\033[0m")
            continue
            
    if not resp:
        raise RuntimeError("All Chairman fallback attempts failed to start.")
        
    print(f"\033[96m🤖 Chairman ({target_model}):\033[0m\n", end="", flush=True)
    
    assistant_reply = ""
    was_reasoning = False
    reasoning_start_time = None
    accumulated_reasoning = ""
    for chunk in resp:
        if not getattr(chunk, "choices", None) or len(chunk.choices) == 0:
            continue
        delta = chunk.choices[0].delta
        
        reasoning = getattr(delta, "reasoning_content", None)
        if reasoning:
            if not was_reasoning:
                was_reasoning = True
                reasoning_start_time = time.time()
                accumulated_reasoning = ""
            accumulated_reasoning += reasoning
            elapsed = time.time() - reasoning_start_time
            snippet = accumulated_reasoning.replace("\n", " ").replace("\r", " ")
            if len(snippet) > 60:
                snippet = "..." + snippet[-57:]
            sys.stdout.write(f"\r\033[K\033[90m[Thinking {elapsed:.1f}s] {snippet}\033[0m")
            sys.stdout.flush()
            
        content = getattr(delta, "content", None)
        if content:
            if was_reasoning:
                sys.stdout.write("\r\033[K")
                sys.stdout.flush()
                was_reasoning = False
                
            print(content, end="", flush=True)
            assistant_reply += content
            
    if was_reasoning:
        sys.stdout.write("\r\033[K")
        sys.stdout.flush()
    print()
    
    is_paid = "free" not in chairman_model.lower() and "nvidia" not in chairman_model.lower()
    if is_paid:
        approx_tokens = len(assistant_reply) / 4
        global SESSION_COST
        if "deepseek-r1" in target_model.lower():
            SESSION_COST += approx_tokens * 0.0000016
        else:
            SESSION_COST += approx_tokens * 0.00001
            
    return assistant_reply


def cleanup_terminal():
    sys.stdout.write("\033[?2004l")
    sys.stdout.flush()

atexit.register(cleanup_terminal)

def read_prompt():
    """Read a prompt from stdin using cbreak mode to prevent terminal freezes
    and handle large bracketed pastes of any size on macOS/Linux.
    """
    # Enable bracketed paste mode in terminal
    sys.stdout.write("\033[?2004h")
    sys.stdout.flush()

    fd = sys.stdin.fileno()
    
    # If not a TTY (piped input), read all of stdin
    if not os.isatty(fd):
        content = sys.stdin.read()
        cleanup_terminal()
        if not content:
            raise EOFError()
        return content.rstrip("\r\n")

    # Display prompt
    sys.stdout.write("\n\033[92m>>> \033[0m")
    sys.stdout.flush()

    old_settings = termios.tcgetattr(fd)
    try:
        # Set to cbreak mode, and disable ECHO
        tty.setcbreak(fd)
        new_settings = termios.tcgetattr(fd)
        new_settings[3] = new_settings[3] & ~termios.ECHO
        termios.tcsetattr(fd, termios.TCSADRAIN, new_settings)
        
        buffer = []
        
        while True:
            # Read 1 character
            char = sys.stdin.read(1)
            if not char:
                raise EOFError()
                
            # Handle Escape sequences (like arrow keys, bracketed paste)
            if char == "\x1b":
                # Check if more characters are available immediately
                seq = [char]
                while True:
                    # Sniff if more characters are available immediately
                    r, _, _ = select.select([sys.stdin], [], [], 0.05)
                    if not r:
                        break
                    next_c = sys.stdin.read(1)
                    seq.append(next_c)
                    seq_str = "".join(seq)
                    if seq_str == "\x1b[200~" or seq_str == "\x1b[201~":
                        break
                    if len(seq) >= 8:
                        break
                        
                seq_str = "".join(seq)
                if seq_str == "\x1b[200~":
                    # Paste start detected! Read until we see the paste end sequence \x1b[201~
                    paste_chars = []
                    while True:
                        c = sys.stdin.read(1)
                        if not c:
                            break
                        paste_chars.append(c)
                        if "".join(paste_chars[-6:]) == "\x1b[201~":
                            paste_chars = paste_chars[:-6]
                            break
                    pasted_text = "".join(paste_chars)
                    buffer.extend(list(pasted_text))
                    sys.stdout.write(pasted_text)
                    sys.stdout.flush()
                    continue
                elif seq_str == "\x1b[201~":
                    # Ignore stray paste end codes
                    continue
                else:
                    # Ignore other escape sequences (like arrow keys)
                    continue
            
            # Handle Ctrl-V (macOS Clipboard Image Paste shortcut)
            if char == "\x16":
                if check_clipboard_has_image():
                    sys.stdout.write("\n\033[92m[Ctrl+V] Detected image in macOS clipboard. Saving...\033[0m\n")
                    sys.stdout.flush()
                    dest = os.path.abspath(".rm_pasted_image.png")
                    ext = extract_clipboard_image(dest)
                    if ext:
                        sys.stdout.write(f"\033[92m[Ctrl+V] Image saved to {dest}.\033[0m\n")
                        sys.stdout.write("\033[93mEnter prompt for image (default: 'Describe this image in detail'): \033[0m")
                        sys.stdout.flush()
                        
                        # Temporarily restore settings to read a whole line for prompt
                        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
                        try:
                            user_prompt = sys.stdin.readline().strip()
                        finally:
                            # Re-enable cbreak mode
                            tty.setcbreak(fd)
                            new_settings = termios.tcgetattr(fd)
                            new_settings[3] = new_settings[3] & ~termios.ECHO
                            termios.tcsetattr(fd, termios.TCSADRAIN, new_settings)
                            
                        if not user_prompt:
                            user_prompt = "Describe this image in detail and summarize the key information shown."
                            
                        return f"/paste {user_prompt}"
                    else:
                        sys.stdout.write("\033[91m[Ctrl+V] Error extracting image from clipboard.\033[0m\n>>> ")
                        sys.stdout.flush()
                else:
                    sys.stdout.write("\033[93m[Ctrl+V] No image found in macOS clipboard. Copy an image first.\033[0m\n>>> ")
                    sys.stdout.flush()
                continue

            # Handle Ctrl-D (EOF)
            if char == "\x04":
                if not buffer:
                    raise EOFError()
                continue
                
            # Handle Backspace / Delete
            if char in ("\x7f", "\b"):
                if buffer:
                    popped = buffer.pop()
                    if popped in ("\n", "\r"):
                        sys.stdout.write("\033[A")
                    else:
                        sys.stdout.write("\b \b")
                    sys.stdout.flush()
                continue
                
            # Handle Enter (Newline)
            if char in ("\n", "\r"):
                sys.stdout.write("\n")
                sys.stdout.flush()
                break
                
            # Normal character
            buffer.append(char)
            sys.stdout.write(char)
            sys.stdout.flush()
            
    finally:
        # Restore terminal settings
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
        cleanup_terminal()
        
    return "".join(buffer)

def handle_exit(messages):
    print(f"\n\033[92mConversation saved to {TEMP_MEM_FILE}. Exiting.\033[0m")
    cleanup_terminal()

def repl(model, use_deep_context=False):
    global WORKSPACE, TEMP_MEM_FILE, SESSION_COST, daily_requests, request_timestamps
    
    if model != "smart" and model != "council":
        client, target_model = get_client_and_model(model)
        print(f"🦾 Universal Chat REPL — model: {model} (Target: {target_model})")
    elif model == "council":
        client, target_model = None, None
        print(f"🦾 LLM Council Deliberation REPL")
    else:
        client, target_model = None, None
        print(f"🧠 Smart Router REPL")
        
    print("Type your message. Exit with Ctrl-D or empty line.\n")
    
    messages = load_temp_memory()
    if messages:
        print("\033[90m[Loaded previous session history. Type /clear to start fresh.]\033[0m")
        if model == "smart":
            target_model, task_type = smart_route(messages[-1]["content"] if len(messages)>1 else "resume")
            if target_model != "council":
                client, target_model = get_client_and_model(target_model)
            else:
                client, target_model = None, None
            
    if not messages:
        if use_deep_context:
            context_str = get_deep_context()
        else:
            context_str = get_instant_context()
            
        system_instruction = (
            "You are a rigorous analytical assistant trained on Charlie Munger's mental models. "
            "1. INVERSION: Identify failure paths and how to avoid them.\n"
            "2. FIRST PRINCIPLES: Strip away assumptions; answer from the irreducible truth.\n"
            "3. NO FLUFF: Avoid generic advice. Give clear, specific, actionable insights.\n"
            f"Context:\n{context_str}"
        )
        messages = [{"role": "system", "content": system_instruction}]

    while True:
        try:
            line = read_prompt()
        except (EOFError, KeyboardInterrupt):
            handle_exit(messages)
            break
            
        if not line.strip():
            continue
            
        line_stripped = line.strip().lower()
            
        if line_stripped in ["exit", "quit", "/exit", "/quit"]:
            handle_exit(messages)
            break
            
        if line_stripped == "/clear":
            if os.path.exists(TEMP_MEM_FILE):
                os.remove(TEMP_MEM_FILE)
            system_instruction = (
                "You are a rigorous analytical assistant trained on Charlie Munger's mental models. "
                "1. INVERSION: Identify failure paths and how to avoid them.\n"
                "2. FIRST PRINCIPLES: Strip away assumptions; answer from the irreducible truth.\n"
                "3. NO FLUFF: Avoid generic advice. Give clear, specific, actionable insights.\n"
                f"Context:\n{get_instant_context()}"
            )
            messages = [{"role": "system", "content": system_instruction}]
            print("\033[93mConversation history cleared.\033[0m")
            continue
            
        # Clipboard Image Paste / Vision command
        if line_stripped.startswith(("/paste", "/image", "/img", "/v")) and not line_stripped.startswith("/workspace") and not line_stripped.startswith("/restore"):
            is_match = False
            for cmd_pref in ["/paste", "/image", "/img", "/v"]:
                if line_stripped.startswith(cmd_pref + " ") or line_stripped == cmd_pref:
                    is_match = True
                    break
            if is_match:
                parts = line.split(" ", 1)
                user_prompt = parts[1].strip() if len(parts) > 1 and parts[1].strip() else ""
                
                # Check clipboard
                if check_clipboard_has_image():
                    dest = os.path.abspath(".rm_pasted_image.png")
                    ext = extract_clipboard_image(dest)
                    if ext:
                        if not user_prompt:
                            user_prompt = "Describe this image in detail and summarize the key information shown."
                        print(f"\033[92m[Vision] Extracted image from clipboard and saved to {dest}.\033[0m")
                        print(f"\033[93m[Vision] Prompt: {user_prompt}\033[0m")
                        reply = run_vision_query(dest, user_prompt)
                        if reply:
                            messages.append({"role": "user", "content": f"[Image attached: {dest}] {user_prompt}"})
                            messages.append({"role": "assistant", "content": reply})
                            save_temp_memory(messages)
                    else:
                        print("\033[91m[Vision] Error extracting image from clipboard.\033[0m")
                else:
                    print("\033[91m[Vision] No image found in macOS clipboard. Copy an image first (Command+C).\033[0m")
                continue

        # Council Deliberation Command
        if line_stripped.startswith(("/council ", "/mc ")) or line_stripped in ("/council", "/mc"):
            parts = line.split(" ", 1)
            if len(parts) > 1 and parts[1].strip():
                council_prompt = parts[1].strip()
                reply = run_council(council_prompt, use_deep_context=use_deep_context)
                messages.append({"role": "user", "content": line})
                messages.append({"role": "assistant", "content": reply})
                save_temp_memory(messages)
            else:
                print("\033[91mUsage: /council <prompt> or /MC <prompt>\033[0m")
            continue
            
        # 1. Context Pinning & Agent Workspaces
        if line_stripped.startswith("/workspace"):
            parts = line.split(" ", 1)
            if len(parts) > 1 and parts[1].strip():
                WORKSPACE = parts[1].strip()
                TEMP_MEM_FILE = f".rm_session_{WORKSPACE}.json"
                messages = load_temp_memory() or [{"role": "system", "content": f"You are a helpful assistant. Context:\n{get_instant_context()}"}]
                print(f"\033[92mSwitched to workspace: {WORKSPACE}\033[0m")
            else:
                print("\033[91mUsage: /workspace <name>\033[0m")
            continue
            
        if line_stripped.startswith("/pin"):
            parts = line.split(" ", 1)
            if len(parts) > 1 and parts[1].strip():
                filepath = parts[1].strip()
                # BUG-02 FIX: Restrict to files within the current working directory
                cwd = Path(os.getcwd()).resolve()
                resolved = (cwd / filepath).resolve()
                if not str(resolved).startswith(str(cwd)):
                    print(f"\033[91mBlocked: /pin only allows files inside the current project directory.\033[0m")
                    continue
                if resolved.exists():
                    with open(resolved, "r") as f:
                        content = f.read()
                    PINNED_CONTEXT.append({"role": "system", "content": f"[PINNED FILE: {filepath}]\\n{content}"})
                    print(f"\033[92mPinned {filepath} to context permanently.\033[0m")
                else:
                    print(f"\033[91mFile not found: {filepath}\033[0m")
            else:
                print("\033[91mUsage: /pin <filepath>\033[0m")
            continue
            
        # 2. Auto-Commit & Failsafe Restore
        if line_stripped == "/safe":
            print("\033[93mCreating failsafe snapshot...\033[0m")
            subprocess.run("git add . && git commit -m 'Auto-backup before AI changes'", shell=True)
            # Record the exact SHA so /restore can be precise
            try:
                global _SAFE_COMMIT_SHA
                _SAFE_COMMIT_SHA = subprocess.check_output(
                    ["git", "rev-parse", "HEAD"], text=True
                ).strip()
                print(f"\033[92mSnapshot created! SHA: {_SAFE_COMMIT_SHA[:8]}. Type /restore to undo future changes.\033[0m")
            except Exception:
                print("\033[92mSnapshot created! Type /restore to undo future changes.\033[0m")
            continue
            
        if line_stripped == "/restore":
            if not _SAFE_COMMIT_SHA:
                print("\033[91mNo /safe snapshot found in this session. Run /safe first.\033[0m")
                continue
            print(f"\033[91mRestoring to /safe snapshot ({_SAFE_COMMIT_SHA[:8]})...\033[0m")
            subprocess.run(["git", "reset", "--hard", _SAFE_COMMIT_SHA])
            print("\033[92mRestored successfully.\033[0m")
            continue
            
        # 3. Global /save Hook
        if line_stripped == "/save":
            print("\033[93m[Global Hook] Triggering save_handler.py to update project memory...\033[0m")
            save_script = os.path.expanduser("~/Projects/RoutingMagic/save_handler.py")
            subprocess.run(f"python3 {save_script}", shell=True)
            continue
            
        # 4. Token Rate Limits & Cost Tracker
        if line_stripped == "/cost":
            rpm = len(request_timestamps)
            print(f"\033[96mSession Cost (Paid): \033[0m ${SESSION_COST:.4f} / ${MAX_BUDGET:.2f} max")
            print(f"\033[96mRate Limits (Free): \033[0m {rpm} RPM (Limit: ~40), {daily_requests} Requests today.")
            continue
            
        # 4. Context-Aware /model Switcher
        if line_stripped == "/model":
            last_msg = messages[-1]["content"] if len(messages) > 1 else "general"
            suggested_model, task_type = smart_route(last_msg)
            
            models_list = [
                ("smart", "Auto (Smart Router)"),
                ("google/gemma-4-31b-it:free", "Gemma-4 31B · OpenRouter (Best Free General)"),
                ("qwen/qwen3-coder:free", "Qwen3 Coder 480B · OpenRouter (Best Free Code)"),
                ("nvidia/nemotron-3-super-120b-a12b:free", "Nemotron 3 Super 120B · OpenRouter (Reasoning & 1M Context)"),
                ("deepseek/deepseek-r1", "DeepSeek R1 · OpenRouter (Paid Reasoning Anchor)"),
                ("meta-llama/llama-3.3-70b-instruct:free", "Llama-3.3 70B · OpenRouter (Tools/JSON)"),
                ("nvidia/llama-3.3-nemotron-super-49b-v1.5", "Nemotron Super 49B · NIM (Flagship)"),
                ("gemini-2.5-pro", "Gemini 2.5 Pro · Google (Paid Anchor)"),
                ("claude-3-7-sonnet-20250219", "Claude Sonnet 3.7 · Anthropic (Paid Anchor)")
            ]
            
            print("\n\033[96mInteractive Model Switcher\033[0m")
            print(f"Context detected: \033[93m{task_type}\033[0m")
            for i, (m_id, desc) in enumerate(models_list):
                prefix = "🌟 " if m_id == suggested_model else "   "
                if m_id == "smart": prefix = "   "
                print(f"{prefix}[{i}] {desc}")
                
            sys.stdout.write("Select model (0-5): ")
            sys.stdout.flush()
            choice = sys.stdin.readline().strip()
            try:
                idx = int(choice)
                if 0 <= idx < len(models_list):
                    model = models_list[idx][0]
                    if model == "smart":
                        client, target_model = None, None
                        print("\033[92mSwitched to Auto (Smart Router)\033[0m")
                    else:
                        client, target_model = get_client_and_model(model)
                        print(f"\033[92mSwitched to {model}\033[0m")
            except:
                print("Invalid choice, keeping current model.")
            continue
            
        # 5. Smart Error Interception & Auto-Testing
        if line.startswith("/run ") or line.startswith("!") or line.startswith("/test "):
            is_test = line.startswith("/test ")
            cmd = line[6:].strip() if is_test else (line[5:].strip() if line.startswith("/run ") else line[1:].strip())
            
            # BUG-01 FIX: Block shell injection metacharacters
            safe, reason = _sanitize_cmd(cmd)
            if not safe:
                print(f"\033[91m{reason}\033[0m")
                continue

            print(f"\033[93mRunning: {cmd}\033[0m")
            # shlex.split parses the command string into a proper argv list
            # so shell=False works correctly with multi-word commands like "npm start"
            try:
                cmd_list = shlex.split(cmd)
            except ValueError as e:
                print(f"\033[91mInvalid command syntax: {e}\033[0m")
                continue
            res = subprocess.run(cmd_list, shell=False, capture_output=True, text=True)
            if res.stdout:
                print(res.stdout)
                
            if res.returncode != 0:
                err = res.stderr or res.stdout
                print(f"\033[91mCommand failed! Error output captured.\033[0m")
                
                if is_test:
                    print("\033[93mAuto-correcting test failure...\033[0m")
                    line = f"The test `{cmd}` failed with this error:\\n```\\n{err[:2000]}\\n```\\nPlease explain the error and provide the corrected code."
                else:
                    sys.stdout.write("Would you like me to explain and fix this error? (y/N): ")
                    sys.stdout.flush()
                    ans = sys.stdin.readline().strip()
                    if ans.lower() == 'y':
                        line = f"I ran `{cmd}` and it failed with this error:\\n```\\n{err[:2000]}\\n```\\nPlease explain why and how to fix it."
                    else:
                        continue
            else:
                if is_test:
                    print("\033[92mTests passed!\033[0m")
                continue

        # Generate LLM response
        if model == "smart":
            target_model, task_type = smart_route(line)
            print(f"\033[94m[Smart Router] Selected '{target_model}' for task type: {task_type}\033[0m")
            
        messages.append({"role": "user", "content": line})
        
        # BUG-04 FIX: Only update target_model when the smart-routed model itself succeeds
        # Track the originally smart-routed model to avoid stale fallback bleeding
        smart_routed_model = target_model if model == "smart" else None

        # Priority Fallback Chain
        # OpenRouter model IDs must NOT have an "openrouter/" prefix — use vendor/model:free format directly
        fallback_chain = [target_model, "google/gemma-4-31b-it:free", "nvidia/nemotron-3-super-120b-a12b:free", "openai/gpt-oss-120b:free", "qwen/qwen3-coder:free", "meta-llama/llama-3.3-70b-instruct:free", "gemini-2.5-pro"]
        # Remove duplicates while preserving order
        seen = set()
        fallback_chain = [x for x in fallback_chain if not (x in seen or seen.add(x))]
        
        success = False
        assistant_reply = ""
        
        for attempt_model in fallback_chain:
            if attempt_model == "council":
                try:
                    print(f"\n\033[96m🤖 assistant (council):\033[0m\n", end="", flush=True)
                    assistant_reply = run_council(line, use_deep_context=use_deep_context)
                    success = True
                    # BUG-04 FIX: Only update target_model if this was the originally intended model
                    if model == "smart" and smart_routed_model and attempt_model == smart_routed_model:
                        target_model = "council"
                    elif model != "smart":
                        target_model = "council"
                    break
                except Exception as e:
                    print(f"\n\033[91m[Error with council] {e}\033[0m")
                    if attempt_model != fallback_chain[-1]:
                        print("\033[93mTrying fallback model...\033[0m")
                    continue

            is_paid = "free" not in attempt_model.lower() and "nvidia" not in attempt_model.lower()
            if is_paid and SESSION_COST >= MAX_BUDGET:
                print(f"\033[91mBudget cap (${MAX_BUDGET}) reached. Skipping paid fallback.\033[0m")
                continue
                
            try:
                temp_client, temp_target = get_client_and_model(attempt_model)
                extra_body = {}
                if "nemotron-3-ultra" in temp_target:
                    extra_body = {"chat_template_kwargs": {"enable_thinking": True}, "reasoning_budget": 4096}
                elif "deepseek-v4-flash" in temp_target:
                    extra_body = {"chat_template_kwargs": {"thinking": True, "reasoning_effort": "high"}}

                print(f"\n\033[96m🤖 assistant ({temp_target}):\033[0m\n", end="", flush=True)

                full_messages = PINNED_CONTEXT + messages

                # o3-mini and o1 family do NOT accept a temperature param — omit it for those
                base_model_id = temp_target.split("/")[-1].split(":")[0]  # e.g. "o3-mini"
                supports_temperature = base_model_id not in NO_TEMPERATURE_MODELS
                kwargs = {
                    "model": temp_target,
                    "messages": full_messages,
                    "stream": True
                }
                if supports_temperature:
                    kwargs["temperature"] = 0.7
                if extra_body:
                    kwargs["extra_body"] = extra_body

                resp = temp_client.chat.completions.create(**kwargs)
                
                now = time.time()
                request_timestamps = [t for t in request_timestamps if now - t < 60]
                request_timestamps.append(now)
                daily_requests += 1
                
                was_reasoning = False
                reasoning_start_time = None
                accumulated_reasoning = ""
                for chunk in resp:
                    if not getattr(chunk, "choices", None) or len(chunk.choices) == 0:
                        continue
                    delta = chunk.choices[0].delta
                    
                    reasoning = getattr(delta, "reasoning_content", None)
                    if reasoning:
                        if not was_reasoning:
                            was_reasoning = True
                            reasoning_start_time = time.time()
                            accumulated_reasoning = ""
                        accumulated_reasoning += reasoning
                        elapsed = time.time() - reasoning_start_time
                        snippet = accumulated_reasoning.replace("\n", " ").replace("\r", " ")
                        if len(snippet) > 60:
                            snippet = "..." + snippet[-57:]
                        sys.stdout.write(f"\r\033[K\033[90m[Thinking {elapsed:.1f}s] {snippet}\033[0m")
                        sys.stdout.flush()
                        
                    content = getattr(delta, "content", None)
                    if content:
                        if was_reasoning:
                            sys.stdout.write("\r\033[K")
                            sys.stdout.flush()
                            was_reasoning = False
                            
                        print(content, end="", flush=True)
                        assistant_reply += content
                if was_reasoning:
                    sys.stdout.write("\r\033[K")
                    sys.stdout.flush()
                print()
                
                if is_paid:
                    # Approximate tokens (1 token ≈ 4 chars) then apply per-model rate
                    approx_tokens = len(assistant_reply) / 4
                    if "deepseek-r1" in temp_target.lower():
                        SESSION_COST += approx_tokens * 0.0000016
                    else:
                        SESSION_COST += approx_tokens * 0.00001  # ~$10/M tokens
                    
                success = True
                # BUG-04 FIX: Only update target_model if this was the originally intended model
                if model == "smart" and smart_routed_model and attempt_model == smart_routed_model:
                    target_model = temp_target
                elif model != "smart":
                    target_model = temp_target
                break 
                
            except Exception as e:
                print(f"\n\033[91m[Error with {attempt_model}] {e}\033[0m")
                if attempt_model != fallback_chain[-1]:
                    print("\033[93mTrying fallback model...\033[0m")
                continue
                
        if not success:
            print("\033[91mAll models in the fallback chain failed.\033[0m")
            messages.pop()
            continue
            
        messages.append({"role": "assistant", "content": assistant_reply})
        save_temp_memory(messages)
        
        if len(messages) > 8:
            messages = compress_context(messages)
            save_temp_memory(messages)

def main():
    if len(sys.argv) < 2:
        sys.stderr.write("Usage: openai_wrapper.py <model_id|smart> [deep] [prompt...]\\n")
        sys.exit(1)
        
    model_id = sys.argv[1]
    args = sys.argv[2:]
    
    # Map 'smart council' argument structure to 'council' model mode
    if model_id == "smart" and args and args[0] == "council":
        model_id = "council"
        args.pop(0)
        
    # Map 'smart /paste' argument structure
    if model_id == "smart" and args and args[0] in ["/paste", "/image", "/img", "/v"]:
        model_id = args[0]
        args.pop(0)
        
    if model_id in ["/paste", "/image", "/img", "/v"]:
        prompt = " ".join(args) if args else "Describe this image in detail and summarize the key information shown."
        if check_clipboard_has_image():
            dest = os.path.abspath(".rm_pasted_image.png")
            ext = extract_clipboard_image(dest)
            if ext:
                print(f"\033[92m[Vision] Extracted image from clipboard and saved to {dest}.\033[0m")
                print(f"\033[93m[Vision] Prompt: {prompt}\033[0m")
                run_vision_query(dest, prompt)
            else:
                print("\033[91m[Vision] Error extracting image from clipboard.\033[0m")
        else:
            print("\033[91m[Vision] No image found in macOS clipboard. Copy an image first (Command+C).\033[0m")
        sys.exit(0)
        
    use_deep = False
    if args and args[0] in ["deep", "--deep"]:
        use_deep = True
        args.pop(0)
        
    if "--resume" in args:
        if not os.path.exists(SESSION_DIR):
            print("No saved sessions found.")
            sys.exit(0)
        sessions = [d for d in os.listdir(SESSION_DIR) if os.path.isdir(os.path.join(SESSION_DIR, d))]
        if not sessions:
            print("No saved sessions found.")
            sys.exit(0)
            
        print("Available Sessions:")
        for i, s in enumerate(sessions):
            print(f"[{i}] {s}")
        
        try:
            sys.stdout.write("Select session to resume: ")
            sys.stdout.flush()
            choice = int(sys.stdin.readline().strip())
            if choice < 0 or choice >= len(sessions):
                raise IndexError("out of range")
            sel = sessions[choice]
            mem_path = os.path.join(SESSION_DIR, sel, "memory.md")
            # Convert the markdown file into a proper JSON messages array
            with open(mem_path, "r") as mf:
                md_content = mf.read()
            session_messages = [
                {"role": "system", "content": f"Resumed session context:\n{md_content}"}
            ]
            with open(TEMP_MEM_FILE, "w") as jf:
                json.dump(session_messages, jf)
            print(f"Loaded session {sel}.")
            repl(model_id, use_deep_context=use_deep)
        except (IndexError, ValueError):
            print("Invalid selection.")
        except Exception as e:
            print(f"Session load error: {e}")
        sys.exit(0)
        
    if len(args) == 0:
        repl(model_id, use_deep_context=use_deep)
    else:
        prompt = " ".join(args)
        chat_oneshot(model_id, prompt, use_deep_context=use_deep)

if __name__ == "__main__":
    main()
