#!/usr/bin/env python3
"""Universal Chat Wrapper & Smart Router

Supports:
  - NVIDIA NIM models (glm-5.1, deepseek-v4-flash, nemotron, etc.)
  - OpenAI models
  - OpenRouter / local 9Router models (free/paid)
  - Smart Routing: Auto-selects the best NVIDIA free model based on task.
  - Dual-Tier Context: Instant context sniffing or deep codebase summarization.
  - Fallback loops, cost tracking, workspaces, failsafes, error interception.
"""
import os
import sys
import socket
import re
import json
import subprocess
import shutil
import time
import select
from pathlib import Path
from openai import OpenAI
from dotenv import load_dotenv

# --- Shell command security helpers ---
# Characters that enable subshell execution or command chaining
_SHELL_DANGEROUS = re.compile(r'[;|&`$<>]|\$\(')

def _sanitize_cmd(cmd: str) -> tuple[bool, str]:
    """Return (is_safe, reason). Blocks shell metacharacters."""
    if _SHELL_DANGEROUS.search(cmd):
        return False, f"Blocked: command contains unsafe shell characters: {_SHELL_DANGEROUS.search(cmd).group()!r}"
    return True, ""

_SAFE_COMMIT_SHA: str | None = None

# Load the env file to ensure all keys are accessible
load_dotenv(os.path.expanduser("~/Projects/investogram/.env"))
load_dotenv(os.path.expanduser("~/global.env"))

WORKSPACE = "default"
TEMP_MEM_FILE = f".rm_session_{WORKSPACE}.json"
SESSION_DIR = os.path.expanduser("~/Projects/RoutingMagic/sessions")

SESSION_COST = 0.0
MAX_BUDGET = 5.0
PINNED_CONTEXT = []
request_timestamps = []
daily_requests = 0

# Mapping of NVIDIA NIM models to their specific API keys
NVIDIA_API_MAP = {
    "nvidia/nemotron-3-ultra-550b-a55b": "NVAPI_KEY_NEMOTRON_ULTRA_550B",
    "nvidia/llama-3.3-nemotron-super-49b-v1.5": "NVAPI_KEY_NEMOTRON_SUPER_49B",
    "nvidia/llama-3.1-nemotron-nano-vl-8b-v1": "NVAPI_KEY_NEMOTRON_VL_8B",
    "nvidia/nvidia-nemotron-nano-9b-v2": "NVAPI_KEY_NEMOTRON_NANO_9B",
    "nvidia/nemotron-ocr-v1": "NVAPI_KEY_NEMOTRON_OCR",
    "nvidia/nemotron-voicechat": "NVAPI_KEY_NEMOTRON_VOICECHAT",
    "nvidia/nv-embedqa-e5-v5": "NVAPI_KEY_NV_EMBEDQA",
    "deepseek-ai/deepseek-v4-flash": "NVAPI_KEY_DEEPSEEK_V4_FLASH",
    "moonshotai/kimi-k2.6": "NVAPI_KEY_KIMI_K2_6",
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": "NVAPI_KEY_NEMOTRON_OMNI_30B",
    "nvidia/nemotron-3.5-content-safety": "NVAPI_KEY_NEMOTRON_SAFETY",
    "mistralai/mistral-medium-3.5-128b": "NVAPI_KEY_MISTRAL_MEDIUM",
    "stepfun-ai/step-3.7-flash": "NVAPI_KEY_STEP_FLASH",
    "google/gemma-4-31b-it": "NVAPI_KEY_GEMMA_31B",
    "minimaxai/minimax-m2.7": "NVAPI_KEY_MINIMAX",
    "nvidia/cosmos3-nano-reasoner": "NVAPI_KEY_COSMOS",
    "nvidia/z-ai/glm-5.1": "NVAPI_KEY"
}

def get_instant_context():
    """Builds a ~150 token context string in milliseconds without calling any APIs."""
    cwd = os.getcwd()
    project_name = os.path.basename(cwd)
    tech_stack = []
    
    if os.path.exists("package.json"):
        try:
            with open("package.json", "r") as f:
                data = json.load(f)
                deps = list(data.get("dependencies", {}).keys()) + list(data.get("devDependencies", {}).keys())
                tech_stack.extend(deps[:15])
        except Exception:
            pass
    if os.path.exists("requirements.txt"):
        tech_stack.append("Python dependencies present")
        
    readme_snippet = ""
    if os.path.exists("README.md"):
        try:
            with open("README.md", "r") as f:
                lines = f.readlines()
                readme_snippet = "".join(lines[:5]).strip()
        except Exception:
            pass
            
    try:
        dirs = [d for d in os.listdir(".") if os.path.isdir(d) and not d.startswith(".")]
    except Exception:
        dirs = []
        
    context = f"Project Context:\n- Directory: {cwd} (Name: {project_name})\n"
    if tech_stack:
        context += f"- Tech Stack/Dependencies: {', '.join(tech_stack)}\n"
    if dirs:
        context += f"- Root Folders: {', '.join(dirs[:10])}\n"
    if readme_snippet:
        context += f"- README excerpt: {readme_snippet}\n"
        
    return context

def get_deep_context():
    """Builds a comprehensive codebase payload and uses a fast model to summarize it."""
    cwd = os.getcwd()
    project_name = os.path.basename(cwd)
    
    # 1. First priority: Check for documentation/history files generated by Claude Code
    history_files = ["memory.md", "progress.md", "scratchpad.md", "lessons.md"]
    found_docs = {}
    for f in history_files:
        if os.path.exists(f):
            try:
                with open(f, "r") as fd:
                    content_snippet = fd.read().strip()
                    if content_snippet:
                        found_docs[f] = content_snippet
            except Exception:
                pass
                
    if found_docs:
        print("\033[92m[Smart Router] Found project history files. Using them for deep context directly.\033[0m")
        combined_context = f"Project Deep Context (extracted from history files in {project_name}):\n\n"
        for name, data in found_docs.items():
            combined_context += f"=== {name} ===\n{data}\n\n"
        return combined_context

    # 2. Fallback: Standard scan & summarization
    content = f"Repository Context for {project_name}:\n\n"
    
    try:
        # Get tree of max 2 levels to avoid huge output
        tree_output = subprocess.check_output(["ls", "-R"], stderr=subprocess.DEVNULL, text=True)
        content += "Directory Tree:\n" + tree_output[:2000] + "\n\n"
    except Exception:
        pass
        
    files_to_read = ["README.md", "package.json", "schema.sql", "schema_v2.sql", "requirements.txt", "pyproject.toml"]
    for f in files_to_read:
        if os.path.exists(f):
            try:
                with open(f, "r") as fd:
                    content += f"--- {f} ---\n{fd.read()[:5000]}\n\n"
            except Exception:
                pass
                
    summarizer_models = ["deepseek-ai/deepseek-v4-flash", "google/gemma-4-31b-it", "mistralai/mistral-medium-3.5-128b"]
    prompt = f"Summarize the architecture, tech stack, and purpose of this codebase based on the following context. Be concise and focus on structural elements useful for a developer.\n\n{content}"
    
    print("\033[93m[Smart Router] Scanning codebase for deep context...\033[0m")
    
    for model in summarizer_models:
        try:
            client, target = get_client_and_model(model, is_summarizer=True)
            kwargs = {
                "model": target,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.3
            }
            if "deepseek-v4-flash" in target:
                kwargs["extra_body"] = {"chat_template_kwargs":{"thinking":True,"reasoning_effort":"low"}}
                
            resp = client.chat.completions.create(**kwargs)
            summary = resp.choices[0].message.content
            print(f"\033[92m[Smart Router] Codebase summarized via {model}.\033[0m")
            return f"Project Deep Context:\n{summary}"
        except Exception as e:
            print(f"\033[91m[Smart Router] Summarizer {model} failed. Trying next...\033[0m")
            
    print("\033[91m[Smart Router] All summarizer models failed. Falling back to instant context.\033[0m")
    return get_instant_context()

def is_port_open(ip, port):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(0.2)
    try:
        s.connect((ip, int(port)))
        s.close()
        return True
    except:
        return False

def smart_route(prompt):
    """Intelligently routes the prompt to the best available free model."""
    prompt_lower = prompt.lower()
    
    # 1. Financial/Math Reasoning & Deep Logic -> DeepSeek R1 (free)
    if re.search(r'\b(math|financial analysis|deep reasoning|o1|complex logic|tradeoffs|step-by-step|chain of thought|deep analysis)\b', prompt_lower):
        return "deepseek/deepseek-r1:free", "financial_math_reasoning"
        
    # 2. Long Document RAG & Heavy Agentic Planning -> Nemotron 3 Super 120B
    if re.search(r'\b(large repo|long doc|architecture|strategy|plan|tool orchestration|codebase reasoning|massive context|rag|planning)\b', prompt_lower):
        return "nvidia/nemotron-3-super-120b-a12b:free", "long_context_agentic"
        
    # 3. Code Generation & Fixing -> Qwen3 Coder
    if re.search(r'\b(code|fix bug|refactor|write function|regex|sql|snippet|debug|react|css|html|typescript|python|script)\b', prompt_lower):
        return "qwen/qwen3-coder:free", "fast_coding"
        
    # 4. Agentic Workflows & Tool Use -> Llama 3.3 70B
    if re.search(r'\b(n8n|tool call|json extraction|workflow|extract data|structure this|json)\b', prompt_lower):
        return "meta-llama/llama-3.3-70b-instruct:free", "n8n_tool_calling"
        
    # 5. Vision / Chart Parsing -> Nemotron VL 8B
    if re.search(r'\b(image|chart|graph|vision|parse screenshot|look at this picture)\b', prompt_lower):
        return "nvidia/llama-3.1-nemotron-nano-vl-8b-v1", "stock_chart_vision"
        
    # 6. Financial Document OCR -> Nemotron OCR v1
    if re.search(r'\b(ocr|pdf|annual report|bse filing|table extraction|scan document)\b', prompt_lower):
        return "nvidia/nemotron-ocr-v1", "financial_doc_ocr"
        
    # 7. Voice / Audio -> Nemotron Voicechat
    if re.search(r'\b(voice|audio|speech|listen|transcribe)\b', prompt_lower):
        return "nvidia/nemotron-voicechat", "voice_trigger"

    # 8. Omni-modal fallback -> Nemotron Nano Omni 30B
    if re.search(r'\b(video|multimodal|omni)\b', prompt_lower):
        return "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning", "multimodal_omni"
        
    # Default General Tasks -> Gemma 4 31B (highest free quality score)
    return "google/gemma-4-31b-it:free", "default_general"

# Models that do NOT accept a temperature parameter
NO_TEMPERATURE_MODELS = {"o3-mini", "o1", "o1-mini", "o1-preview", "o3"}

def get_client_and_model(model_name, is_summarizer=False):
    clean_model = model_name
    # Ensure timeout is snappy so the user doesn't wait forever before failover
    req_timeout = 15 if is_summarizer else 25
    
    # NVIDIA NIM models — identified by presence in map, or by common vendor prefixes
    nvidia_vendors = ("nvidia/", "deepseek-ai/", "moonshotai/", "mistralai/", "google/gemma",
                      "minimaxai/", "stepfun-ai/", "glm")
    if (model_name in NVIDIA_API_MAP or any(model_name.startswith(v) for v in nvidia_vendors) or "glm" in model_name) and not model_name.endswith(":free"):
        # Strip the top-level "nvidia/" org prefix if present (e.g. nvidia/z-ai/glm-5.1 → z-ai/glm-5.1)
        if model_name.startswith("nvidia/") and model_name.count("/") >= 2:
            # e.g. "nvidia/z-ai/glm-5.1" → "z-ai/glm-5.1"
            clean_model = model_name[len("nvidia/"):]
        elif model_name.startswith("nvidia/") and model_name.count("/") == 1:
            # e.g. "nvidia/nemotron-..." — keep as is, NVIDIA API accepts the full ID
            clean_model = model_name
        else:
            clean_model = model_name
            
        key_env_var = NVIDIA_API_MAP.get(model_name, "NVAPI_KEY")
        api_key = os.getenv(key_env_var) or os.getenv("NVAPI_KEY") or os.getenv("NVIDIA_API_KEY")
        base_url = "https://integrate.api.nvidia.com/v1"
        return OpenAI(api_key=api_key, base_url=base_url, timeout=req_timeout), clean_model
    
    # OpenAI direct models (o3-mini, gpt-*, o1-*)
    if model_name.startswith("openai/") or model_name.startswith("gpt-") or model_name.startswith("o1") or model_name.startswith("o3"):
        if model_name.startswith("openai/"):
            clean_model = model_name[len("openai/"):]
        else:
            clean_model = model_name
        api_key = os.getenv("OPENAI_API_KEY")
        return OpenAI(api_key=api_key, timeout=req_timeout), clean_model

    # OpenRouter / 9router — model IDs must NOT have an 'openrouter/' prefix
    # Strip it if accidentally present (e.g. "openrouter/google/gemma..." → "google/gemma...")
    if model_name.startswith("openrouter/"):
        clean_model = model_name[len("openrouter/"):]
    else:
        clean_model = model_name

    if is_port_open("127.0.0.1", 20128):
        base_url = "http://127.0.0.1:20128/v1"
        api_key = "9router-local"
    else:
        base_url = "https://openrouter.ai/api/v1"
        api_key = os.getenv("OPENROUTER_API_KEY") or os.getenv("9ROUTER_API_KEY")
        
    return OpenAI(api_key=api_key, base_url=base_url, timeout=req_timeout), clean_model

def save_temp_memory(messages):
    try:
        with open(TEMP_MEM_FILE, "w") as f:
            json.dump(messages, f)
    except Exception:
        pass

def load_temp_memory():
    if os.path.exists(TEMP_MEM_FILE):
        try:
            with open(TEMP_MEM_FILE, "r") as f:
                return json.load(f)
        except Exception:
            pass
    return None



def compress_context(messages):
    if len(messages) <= 6:
        return messages
    
    sys_msg = messages[0]
    recent_msgs = messages[-3:]
    middle_msgs = messages[1:-3]
    hist = json.dumps(middle_msgs)
    
    prompt = f"Summarize the key technical decisions, bugs fixed, and current goal of this chat history. Be concise.\n\n{hist}"
    
    fallback_chain = ["google/gemma-4-31b-it:free", "nvidia/nemotron-3-super-120b-a12b:free", "qwen/qwen3-coder:free"]
    summary = None
    
    for target_model in fallback_chain:
        try:
            client, target = get_client_and_model(target_model, is_summarizer=True)
            resp = client.chat.completions.create(
                model=target,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3
            )
            summary = resp.choices[0].message.content.strip()
            print(f"\033[92m[Smart Router] Context compressed via {target_model}.\033[0m")
            break
        except Exception as e:
            continue
            
    if not summary:
        return messages
        
    return [
        sys_msg,
        {"role": "assistant", "content": f"[SYSTEM: Previous context summary]\n{summary}"}
    ] + recent_msgs

def chat_oneshot(model, prompt, use_deep_context=False):
    if model == "smart":
        target_model, task_type = smart_route(prompt)
        print(f"\033[94m[Smart Router] Selected '{target_model}' for task type: {task_type}\033[0m")
    else:
        target_model = model

    if use_deep_context:
        context_str = get_deep_context()
    else:
        context_str = get_instant_context()

    system_message = {"role": "system", "content": f"You are a highly capable AI assistant helping a developer. Always incorporate the following project context into your answers to be as specific and useful as possible.\n\n{context_str}"}

    fallback_chain = [target_model, "google/gemma-4-31b-it:free", "nvidia/nemotron-3-super-120b-a12b:free", "openai/gpt-oss-120b:free", "qwen/qwen3-coder:free", "meta-llama/llama-3.3-70b-instruct:free", "gemini-2.5-pro"]
    seen = set()
    fallback_chain = [x for x in fallback_chain if not (x in seen or seen.add(x))]

    success = False
    for attempt_model in fallback_chain:
        try:
            temp_client, final_model_id = get_client_and_model(attempt_model)
            
            extra_body = {}
            if "nemotron-3-ultra" in final_model_id:
                extra_body = {"chat_template_kwargs":{"enable_thinking":True},"reasoning_budget":4096}
            elif "deepseek-v4-flash" in final_model_id:
                extra_body = {"chat_template_kwargs":{"thinking":True,"reasoning_effort":"high"}}
            
            base_model_id = final_model_id.split("/")[-1].split(":")[0]
            supports_temperature = base_model_id not in NO_TEMPERATURE_MODELS
            
            kwargs = {
                "model": final_model_id,
                "messages": [system_message, {"role": "user", "content": prompt}],
                "stream": True
            }
            if supports_temperature:
                kwargs["temperature"] = 0.7
            if extra_body:
                kwargs["extra_body"] = extra_body

            print(f"\n\033[96m🤖 assistant ({final_model_id}):\033[0m\n", end="", flush=True)
            resp = temp_client.chat.completions.create(**kwargs)
            was_reasoning = False
            for chunk in resp:
                if not getattr(chunk, "choices", None) or len(chunk.choices) == 0:
                    continue
                    
                delta = chunk.choices[0].delta
                reasoning = getattr(delta, "reasoning_content", None)
                if reasoning:
                    was_reasoning = True
                    print(f"\033[90m{reasoning}\033[0m", end="", flush=True)
                    
                content = getattr(delta, "content", None)
                if content:
                    if was_reasoning:
                        print("\n\n", end="")
                        was_reasoning = False
                        
                    print(content, end="", flush=True)
            print()
            success = True
            break
        except Exception as e:
            print(f"\n\033[91m[Error with {attempt_model}] {e}\033[0m")
            if attempt_model != fallback_chain[-1]:
                print("\033[93mTrying fallback model...\033[0m")
            continue
            
    if not success:
        raise RuntimeError("All models in the fallback chain failed for chat_oneshot.")


def handle_exit(messages):
    print(f"\n\033[92mConversation saved to {TEMP_MEM_FILE}. Exiting.\033[0m")

def repl(model, use_deep_context=False):
    global WORKSPACE, TEMP_MEM_FILE, SESSION_COST, daily_requests, request_timestamps
    
    if model != "smart":
        client, target_model = get_client_and_model(model)
        print(f"🦾 Universal Chat REPL — model: {model} (Target: {target_model})")
    else:
        client, target_model = None, None
        print(f"🧠 Smart Router REPL")
        
    print("Type your message. Exit with Ctrl-D or empty line.\n")
    
    messages = load_temp_memory()
    if messages:
        print("\033[90m[Loaded previous session history. Type /clear to start fresh.]\033[0m")
        if model == "smart":
            target_model, task_type = smart_route(messages[-1]["content"] if len(messages)>1 else "resume")
            client, target_model = get_client_and_model(target_model)
            
    if not messages:
        if use_deep_context:
            context_str = get_deep_context()
        else:
            context_str = get_instant_context()
        messages = [{"role": "system", "content": f"You are a helpful assistant. Context:\n{context_str}"}]
        
    def read_prompt():
        """Read a prompt from stdin, collecting all lines from a multi-line paste
        into a single string before returning it. This prevents each pasted paragraph
        from being submitted as a separate prompt."""
        try:
            first_line = input("\n\033[92m>>> \033[0m")
        except (EOFError, KeyboardInterrupt):
            raise
        
        # After receiving the first line, check if stdin has more data buffered
        # immediately (i.e. the user pasted a block of text). Drain all of it.
        lines = [first_line]
        while True:
            # select with timeout=0 checks if stdin is readable RIGHT NOW (non-blocking)
            ready, _, _ = select.select([sys.stdin], [], [], 0.05)
            if not ready:
                break  # No more data immediately available — this is a normal keypress
            next_line = sys.stdin.readline()
            if not next_line:
                break  # EOF
            lines.append(next_line.rstrip("\n"))
        
        return "\n".join(lines)

    while True:
        try:
            line = read_prompt()
        except (EOFError, KeyboardInterrupt):
            handle_exit(messages)
            break
            
        if not line.strip():
            continue
            
        line_stripped = line.strip().lower()
            
        if line_stripped in ["exit", "quit", "/exit", "/quit"]:
            handle_exit(messages)
            break
            
        if line_stripped == "/clear":
            if os.path.exists(TEMP_MEM_FILE):
                os.remove(TEMP_MEM_FILE)
            messages = [{"role": "system", "content": f"You are a helpful assistant. Context:\n{get_instant_context()}"}]
            print("\033[93mConversation history cleared.\033[0m")
            continue
            
        # 1. Context Pinning & Agent Workspaces
        if line_stripped.startswith("/workspace"):
            parts = line.split(" ", 1)
            if len(parts) > 1 and parts[1].strip():
                WORKSPACE = parts[1].strip()
                TEMP_MEM_FILE = f".rm_session_{WORKSPACE}.json"
                messages = load_temp_memory() or [{"role": "system", "content": f"You are a helpful assistant. Context:\n{get_instant_context()}"}]
                print(f"\033[92mSwitched to workspace: {WORKSPACE}\033[0m")
            else:
                print("\033[91mUsage: /workspace <name>\033[0m")
            continue
            
        if line_stripped.startswith("/pin"):
            parts = line.split(" ", 1)
            if len(parts) > 1 and parts[1].strip():
                filepath = parts[1].strip()
                # BUG-02 FIX: Restrict to files within the current working directory
                cwd = Path(os.getcwd()).resolve()
                resolved = (cwd / filepath).resolve()
                if not str(resolved).startswith(str(cwd)):
                    print(f"\033[91mBlocked: /pin only allows files inside the current project directory.\033[0m")
                    continue
                if resolved.exists():
                    with open(resolved, "r") as f:
                        content = f.read()
                    PINNED_CONTEXT.append({"role": "system", "content": f"[PINNED FILE: {filepath}]\\n{content}"})
                    print(f"\033[92mPinned {filepath} to context permanently.\033[0m")
                else:
                    print(f"\033[91mFile not found: {filepath}\033[0m")
            else:
                print("\033[91mUsage: /pin <filepath>\033[0m")
            continue
            
        # 2. Auto-Commit & Failsafe Restore
        if line_stripped == "/safe":
            print("\033[93mCreating failsafe snapshot...\033[0m")
            subprocess.run("git add . && git commit -m 'Auto-backup before AI changes'", shell=True)
            # Record the exact SHA so /restore can be precise
            try:
                global _SAFE_COMMIT_SHA
                _SAFE_COMMIT_SHA = subprocess.check_output(
                    ["git", "rev-parse", "HEAD"], text=True
                ).strip()
                print(f"\033[92mSnapshot created! SHA: {_SAFE_COMMIT_SHA[:8]}. Type /restore to undo future changes.\033[0m")
            except Exception:
                print("\033[92mSnapshot created! Type /restore to undo future changes.\033[0m")
            continue
            
        if line_stripped == "/restore":
            if not _SAFE_COMMIT_SHA:
                print("\033[91mNo /safe snapshot found in this session. Run /safe first.\033[0m")
                continue
            print(f"\033[91mRestoring to /safe snapshot ({_SAFE_COMMIT_SHA[:8]})...\033[0m")
            subprocess.run(["git", "reset", "--hard", _SAFE_COMMIT_SHA])
            print("\033[92mRestored successfully.\033[0m")
            continue
            
        # 3. Global /save Hook
        if line_stripped == "/save":
            print("\033[93m[Global Hook] Triggering save_handler.py to update project memory...\033[0m")
            save_script = os.path.expanduser("~/Projects/RoutingMagic/save_handler.py")
            subprocess.run(f"python3 {save_script}", shell=True)
            continue
            
        # 4. Token Rate Limits & Cost Tracker
        if line_stripped == "/cost":
            rpm = len(request_timestamps)
            print(f"\033[96mSession Cost (Paid): \033[0m ${SESSION_COST:.4f} / ${MAX_BUDGET:.2f} max")
            print(f"\033[96mRate Limits (Free): \033[0m {rpm} RPM (Limit: ~40), {daily_requests} Requests today.")
            continue
            
        # 4. Context-Aware /model Switcher
        if line_stripped == "/model":
            last_msg = messages[-1]["content"] if len(messages) > 1 else "general"
            suggested_model, task_type = smart_route(last_msg)
            
            models_list = [
                ("smart", "Auto (Smart Router)"),
                ("google/gemma-4-31b-it:free", "Gemma-4 31B · OpenRouter (Best Free General)"),
                ("qwen/qwen3-coder:free", "Qwen3 Coder 480B · OpenRouter (Best Free Code)"),
                ("nvidia/nemotron-3-super-120b-a12b:free", "Nemotron 3 Super 120B · OpenRouter (1M Context)"),
                ("deepseek/deepseek-r1:free", "DeepSeek R1 · OpenRouter (Math/Reasoning)"),
                ("meta-llama/llama-3.3-70b-instruct:free", "Llama-3.3 70B · OpenRouter (Tools/JSON)"),
                ("nvidia/llama-3.3-nemotron-super-49b-v1.5", "Nemotron Super 49B · NIM (Flagship)"),
                ("gemini-2.5-pro", "Gemini 2.5 Pro · Google (Paid Anchor)"),
                ("claude-3-7-sonnet-20250219", "Claude Sonnet 3.7 · Anthropic (Paid Anchor)")
            ]
            
            print("\n\033[96mInteractive Model Switcher\033[0m")
            print(f"Context detected: \033[93m{task_type}\033[0m")
            for i, (m_id, desc) in enumerate(models_list):
                prefix = "🌟 " if m_id == suggested_model else "   "
                if m_id == "smart": prefix = "   "
                print(f"{prefix}[{i}] {desc}")
                
            choice = input("Select model (0-5): ").strip()
            try:
                idx = int(choice)
                if 0 <= idx < len(models_list):
                    model = models_list[idx][0]
                    if model == "smart":
                        client, target_model = None, None
                        print("\033[92mSwitched to Auto (Smart Router)\033[0m")
                    else:
                        client, target_model = get_client_and_model(model)
                        print(f"\033[92mSwitched to {model}\033[0m")
            except:
                print("Invalid choice, keeping current model.")
            continue
            
        # 5. Smart Error Interception & Auto-Testing
        if line.startswith("/run ") or line.startswith("!") or line.startswith("/test "):
            is_test = line.startswith("/test ")
            cmd = line[6:].strip() if is_test else (line[5:].strip() if line.startswith("/run ") else line[1:].strip())
            
            # BUG-01 FIX: Block shell injection metacharacters
            safe, reason = _sanitize_cmd(cmd)
            if not safe:
                print(f"\033[91m{reason}\033[0m")
                continue

            print(f"\033[93mRunning: {cmd}\033[0m")
            # Use list form (shell=False) to prevent injection
            res = subprocess.run(cmd, shell=False, capture_output=True, text=True)
            if res.stdout:
                print(res.stdout)
                
            if res.returncode != 0:
                err = res.stderr or res.stdout
                print(f"\033[91mCommand failed! Error output captured.\033[0m")
                
                if is_test:
                    print("\033[93mAuto-correcting test failure...\033[0m")
                    line = f"The test `{cmd}` failed with this error:\\n```\\n{err[:2000]}\\n```\\nPlease explain the error and provide the corrected code."
                else:
                    ans = input("Would you like me to explain and fix this error? (y/N): ")
                    if ans.lower() == 'y':
                        line = f"I ran `{cmd}` and it failed with this error:\\n```\\n{err[:2000]}\\n```\\nPlease explain why and how to fix it."
                    else:
                        continue
            else:
                if is_test:
                    print("\033[92mTests passed!\033[0m")
                continue

        # Generate LLM response
        if model == "smart":
            target_model, task_type = smart_route(line)
            print(f"\033[94m[Smart Router] Selected '{target_model}' for task type: {task_type}\033[0m")
            
        messages.append({"role": "user", "content": line})
        
        # BUG-04 FIX: Only update target_model when the smart-routed model itself succeeds
        # Track the originally smart-routed model to avoid stale fallback bleeding
        smart_routed_model = target_model if model == "smart" else None

        # Priority Fallback Chain
        # OpenRouter model IDs must NOT have an "openrouter/" prefix — use vendor/model:free format directly
        fallback_chain = [target_model, "google/gemma-4-31b-it:free", "nvidia/nemotron-3-super-120b-a12b:free", "openai/gpt-oss-120b:free", "qwen/qwen3-coder:free", "meta-llama/llama-3.3-70b-instruct:free", "gemini-2.5-pro"]
        # Remove duplicates while preserving order
        seen = set()
        fallback_chain = [x for x in fallback_chain if not (x in seen or seen.add(x))]
        
        success = False
        assistant_reply = ""
        
        for attempt_model in fallback_chain:
            is_paid = "free" not in attempt_model.lower() and "nvidia" not in attempt_model.lower()
            if is_paid and SESSION_COST >= MAX_BUDGET:
                print(f"\033[91mBudget cap (${MAX_BUDGET}) reached. Skipping paid fallback.\033[0m")
                continue
                
            try:
                temp_client, temp_target = get_client_and_model(attempt_model)
                extra_body = {}
                if "nemotron-3-ultra" in temp_target:
                    extra_body = {"chat_template_kwargs": {"enable_thinking": True}, "reasoning_budget": 4096}
                elif "deepseek-v4-flash" in temp_target:
                    extra_body = {"chat_template_kwargs": {"thinking": True, "reasoning_effort": "high"}}

                print(f"\n\033[96m🤖 assistant ({temp_target}):\033[0m\n", end="", flush=True)

                full_messages = PINNED_CONTEXT + messages

                # o3-mini and o1 family do NOT accept a temperature param — omit it for those
                base_model_id = temp_target.split("/")[-1].split(":")[0]  # e.g. "o3-mini"
                supports_temperature = base_model_id not in NO_TEMPERATURE_MODELS
                kwargs = {
                    "model": temp_target,
                    "messages": full_messages,
                    "stream": True
                }
                if supports_temperature:
                    kwargs["temperature"] = 0.7
                if extra_body:
                    kwargs["extra_body"] = extra_body

                resp = temp_client.chat.completions.create(**kwargs)
                
                now = time.time()
                request_timestamps = [t for t in request_timestamps if now - t < 60]
                request_timestamps.append(now)
                daily_requests += 1
                
                was_reasoning = False
                for chunk in resp:
                    if not getattr(chunk, "choices", None) or len(chunk.choices) == 0:
                        continue
                    delta = chunk.choices[0].delta
                    
                    reasoning = getattr(delta, "reasoning_content", None)
                    if reasoning:
                        was_reasoning = True
                        print(f"\033[90m{reasoning}\033[0m", end="", flush=True)
                        
                    content = getattr(delta, "content", None)
                    if content:
                        if was_reasoning:
                            print("\n\n", end="")
                            was_reasoning = False
                            
                        print(content, end="", flush=True)
                        assistant_reply += content
                print()
                
                if is_paid:
                    # Approximate tokens (1 token ≈ 4 chars) then apply per-model rate
                    approx_tokens = len(assistant_reply) / 4
                    SESSION_COST += approx_tokens * 0.00001  # ~$10/M tokens
                    
                success = True
                # BUG-04 FIX: Only update target_model if this was the originally intended model
                if model == "smart" and smart_routed_model and attempt_model == smart_routed_model:
                    target_model = temp_target
                elif model != "smart":
                    target_model = temp_target
                break 
                
            except Exception as e:
                print(f"\n\033[91m[Error with {attempt_model}] {e}\033[0m")
                if attempt_model != fallback_chain[-1]:
                    print("\033[93mTrying fallback model...\033[0m")
                continue
                
        if not success:
            print("\033[91mAll models in the fallback chain failed.\033[0m")
            messages.pop()
            continue
            
        messages.append({"role": "assistant", "content": assistant_reply})
        save_temp_memory(messages)
        
        if len(messages) > 8:
            messages = compress_context(messages)
            save_temp_memory(messages)

def main():
    if len(sys.argv) < 2:
        sys.stderr.write("Usage: openai_wrapper.py <model_id|smart> [deep] [prompt...]\\n")
        sys.exit(1)
        
    model_id = sys.argv[1]
    args = sys.argv[2:]
    
    use_deep = False
    if args and args[0] in ["deep", "--deep"]:
        use_deep = True
        args.pop(0)
        
    if "--resume" in args:
        if not os.path.exists(SESSION_DIR):
            print("No saved sessions found.")
            sys.exit(0)
        sessions = [d for d in os.listdir(SESSION_DIR) if os.path.isdir(os.path.join(SESSION_DIR, d))]
        if not sessions:
            print("No saved sessions found.")
            sys.exit(0)
            
        print("Available Sessions:")
        for i, s in enumerate(sessions):
            print(f"[{i}] {s}")
        
        try:
            choice = int(input("Select session to resume: "))
            if choice < 0 or choice >= len(sessions):
                raise IndexError("out of range")
            sel = sessions[choice]
            mem_path = os.path.join(SESSION_DIR, sel, "memory.md")
            # Convert the markdown file into a proper JSON messages array
            with open(mem_path, "r") as mf:
                md_content = mf.read()
            session_messages = [
                {"role": "system", "content": f"Resumed session context:\n{md_content}"}
            ]
            with open(TEMP_MEM_FILE, "w") as jf:
                json.dump(session_messages, jf)
            print(f"Loaded session {sel}.")
            repl(model_id, use_deep_context=use_deep)
        except (IndexError, ValueError):
            print("Invalid selection.")
        except Exception as e:
            print(f"Session load error: {e}")
        sys.exit(0)
        
    if len(args) == 0:
        repl(model_id, use_deep_context=use_deep)
    else:
        prompt = " ".join(args)
        chat_oneshot(model_id, prompt, use_deep_context=use_deep)

if __name__ == "__main__":
    main()
