#!/usr/bin/env python3
"""
OpenCode Menu Builder

Produces the ready-to-consume opencode_model_menu.json from the task rankings.
Output format matches opencode.jsonc provider whitelist + display-name structure.
"""
import json, os, sys
from pathlib import Path
from datetime import datetime, timezone
from typing import Dict, List, Any

REPO = Path(__file__).resolve().parents[1]
REGISTRY_DIR = REPO / "registry"
TASK_RANKINGS_FILE = REGISTRY_DIR / "task_rankings.json"
CACHE_FILE = REGISTRY_DIR / "openrouter_catalog.json"
OUTPUT_FILE = REGISTRY_DIR / "opencode_model_menu.json"

# Display name templates (match existing opencode.jsonc naming convention)
def make_name(model_id: str, task: str, rank: str, tier: str) -> str:
    """Generate a display name matching the ★ convention in opencode.jsonc."""
    star = "★" if rank == "primary" else ""
    tier_tag = "[FREE]" if tier == "free" else ""
    return f"{star}{model_id} {tier_tag} {task} {rank}"


def categorize_provider(oid: str) -> str:
    """Map model ID to openrouter or nvidia provider."""
    if oid.startswith(("nvidia/", "deepseek-ai/", "poolside/", "minimaxai/", "moonshotai/", "cohere/", "thinkingmachines/", "dots-studio/")):
        return "nvidia"
    return "openrouter"


def build_menu():
    print("[build_opencode_menu] Loading task rankings...")

    rankings = None
    if TASK_RANKINGS_FILE.exists():
        with open(TASK_RANKINGS_FILE) as f:
            rankings = json.load(f)
    if not rankings:
        print("[build_opencode_menu] No task rankings found. Exiting.")
        sys.exit(1)

    # Build the menu structure
    menu = {
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "note": "Auto-generated by RoutingMagic. Do not edit by hand. Regenerated daily.",
        "providers": {
            "openrouter": {"whitelist": [], "models": {}},
            "nvidia": {"whitelist": [], "models": {}},
        },
    }

    # Collect all scored models, deduplicate by id (prefer primary_free)
    seen = {}
    for task_id, task_data in rankings.get("tasks", {}).items():
        for rank_type in ["primary_free", "secondary_paid"]:
            for m in task_data.get(rank_type, []):
                oid = m["id"]
                if oid.startswith("~"):
                    continue  # skip deprecated/renamed models
                if oid not in seen or (m["rank"] == "primary_free" and seen[oid]["rank"] != "primary_free"):
                    seen[oid] = m

    # Build per-provider whitelists and display names
    provider_models = {"openrouter": [], "nvidia": []}
    for oid in seen:
        prov = categorize_provider(oid)
        provider_models[prov].append(oid)

    # Build whitelists and display names (cap at 50 per provider)
    for prov in ["openrouter", "nvidia"]:
        models_for_prov = provider_models[prov]
        menu["providers"][prov]["whitelist"] = models_for_prov[:50]
        for oid in models_for_prov[:50]:
            m = seen.get(oid, {})
            task = m.get("task", "general")
            rank = m.get("rank", "secondary_paid")
            tier = "free" if m.get("free") else "paid"
            menu["providers"][prov]["models"][oid] = {
                "name": make_name(oid, task, rank, tier),
            }

    # Output
    REGISTRY_DIR.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        json.dump(menu, f, indent=2)

    print(f"[build_opencode_menu] Done. Output: {OUTPUT_FILE}")
    for prov in ["openrouter", "nvidia"]:
        wl = menu["providers"][prov]["whitelist"]
        print(f"  {prov}: {len(wl)} models in whitelist")


if __name__ == "__main__":
    build_menu()
